export interface IKeyValue {
    key: string;
    value: string;
}

export function getString(key: string): string {
    return map.get(key) || key;
}

const strings: IKeyValue[] = [
    { key: "dashboard", value: "Početna" },
    { key: "roomManagement", value: "Upravljanje sobama" },
    { key: "floors", value: "Katevi" },
    { key: "rooms", value: "Sobe" },
    { key: "id", value: "Šifra" },
    { key: "name", value: "Naziv" },
    { key: "capacity", value: "Kapacitet" },
    { key: "floor", value: "Kat" },
    { key: "saveSuccess", value: "Uspješno spremljeno!" },
    { key: "saveError", value: "Pogreška prilikom spremanja!" },
    { key: "noRoomsForSelectedFloor", value: "Nema spremljenih soba za odabrani kat!" },
    { key: "persons", value: "Osobe" },
    { key: "basicData", value: "Osnovni podaci" },
    { key: "firstName", value: "Ime" },
    { key: "lastName", value: "Prezime" },
    { key: "jmbg", value: "JMBG" },
    { key: "birthDate", value: "Datum rođenja" },
    { key: "stayData", value: "Podaci o boravku" },
    { key: "startDate", value: "Datum dolaska" },
    { key: "endDate", value: "Datum odlaska" },
    { key: "creationDate", value: "Datum unosa" },
    { key: "currentStatus", value: "Trenutni status osobe" },
    { key: "active", value: "Aktivan" },
    { key: "unactive", value: "Neaktivan" },
    { key: "activeTooltip", value: "Osoba je trenutno smještena u ustanovi." },
    { key: "unactiveTooltip", value: "Osoba je bila smještena u ustanovi, ali je njen boravak završio." },
    { key: "deactivatePerson", value: "Deaktiviraj osobu" },
    { key: "dormatoryData", value: "Podaci o smještaju" },
    { key: "currentFloor", value: "Kat na kojemu je osoba smještena" },
    { key: "room", value: "Soba" },
    { key: "goToExternalRoomManagement", value: "Idi na vanjsko upravljanje smještajem" },
    { key: "goToAdvancedEdit", value: "Idi na napredno uređivanje" },
    { key: "save", value: "Spremi" },
    { key: "cancel", value: "Odustani" },
    { key: "personData", value: "Podaci o osobi" },
    { key: "activePersonDetails", value: "Aktivna osoba je osoba koja je trenutno smještena u ustanovi." },
    { key: "unactivePersonDetails", value: "Neaktivna osoba je osoba čiji je boravak u ustanovi završio." },
    { key: "changeStatusPersonText1", value: "Za prebacivanje osobe iz statusa aktivne u neaktivnu potrebno je kliknuti gumb: " },
    { key: "changeStatusPersonText2", value: "Ukoliko ne navedete 'Datum odlaska' spremit će se trenutni datum kao datum odlaska osobe iz ustanove." },
    { key: "unactivePersons", value: "Prikaži neaktivne osobe" },
    { key: "areYouSure", value: "Jeste li sigurni?" },
    { key: "questionDeactivatePerson", value: "Želite li deaktivirati osobu s datumom: " },
    { key: "yes", value: "Da" },
    { key: "no", value: "Ne" },
    { key: "search", value: "Pretraživanje" },
    { key: "contacts", value: "Kontakti" },
    { key: "email", value: "E-mail" },
    { key: "telephone", value: "Telefon" },
    { key: "mobile", value: "Mobitel" },
    { key: "noContacts", value: "Nema spremljenih kontakata!" },
    { key: "addPerson", value: "Unos nove osobe" },
    { key: "basicPersonData", value: "Osnovni podaci o osobi" },
    { key: "basicPersonStepText", value: "Ovdje popunite osnovne podatke o novoj osobi. Nakon unosa, klikom na gumb za dodavanje nove osobe, osoba je dodana u sustav. U daljnim koracima možete (ne morate) popuniti neke dodatne podatke o novom korisniku doma, na primjer: unijeti kontakt osobe, dodijeliti sobu za smještaj, bilješke, dokumente i slično." },
    { key: "saveNewPerson", value: "Spremi novu osobu" },
    { key: "back", value: "Nazad" },
    { key: "next", value: "Dalje" },
    { key: "required", value: "Polje je obavezno!" },
    { key: "contactsPersonData", value: "Kontakt osobe" },
    { key: "contactsPersonStepText", value: "Ovdje popunite podatke o kontakt osobama. Možete navesti više kontakt osoba, te za svaku osobu popuniti neku vrstu kontakta (e-mail, telefonski broj ili mobilni broj). Za svaki kontakt obavezno je unijeti ime i prezime." },
    { key: "accomodation", value: "Smještaj" },
    { key: "documents", value: "Dokumenti" },
    { key: "notes", value: "Bilješke" },
    { key: "services", value: "Paket usluga" },
    { key: "savePersonFirst", value: "Za unos prvo spremite osnovne podatke o osobi!" },
    { key: "accomodationPersonStepText", value: "Ovdje popunite podatke o smještaju nove osobe. Osobu možete smjestiti samo u sobu u kojoj ima slobodnog mjesta. U jednoj sobi mogu biti smještene samo osobe istoga spola (obratite pažnju ukoliko već imate osobu u odabranoj sobi!). Podatke možete uređivati i sa portala za upravljanje smještajem." },
    { key: "address", value: "Adresa" },
    { key: "gender", value: "Spol" },
    { key: "freeSpace", value: "Slobodno" },
    { key: "roomSelectionInvalid", value: "Ne možete u istoj sobi imati dodjeljene osobe različitih spolova. U tablici pod stupcem 'Spol' naveden je spol osoba koje su trenutno smještene u sobu." },
    { key: "placePerson", value: "Smjesti osobu" },
    { key: "accomodationManagement", value: "Upravljanje smještajem" },
    { key: "searchPersons", value: "Detaljno pregledavanje osoba" },
    { key: "typeSearchTerm", value: "Za pretraživanje po unesenom pojmu pritisnite ENTER" },
    { key: "searchNoResult", value: "Pretraživanje nije dalo rezultata!" },
    { key: "editData", value: "Uređivanje podataka" },
    { key: "passedTime", value: "Vrijeme provedeno u domu" },
    { key: "years", value: "Godine" },
    { key: "months", value: "Mjeseci" },
    { key: "days", value: "Dani" },
    { key: "currentAccomodation", value: "Podaci o trenutnom smještaju" },
    { key: "history", value: "Povijest promjena" },
    { key: "packagesManagement", value: "Upravljanje paketima usluga" },
    { key: "addNew", value: "Dodavanje podataka" },
    { key: "description", value: "Opis" },
    { key: "calculation", value: "Izračun cijene" },
    { key: "priceCalculated", value: "Cijena paketa temeljena na izračunu" },
    { key: "servicesForPackage", value: "Usluge unutar paketa" },
    { key: "quantity", value: "Količina" },
    { key: "costPerUnit", value: "Jedinična cijena" },
    { key: "measureUnit", value: "Jedinica mjere" },
    { key: "add", value: "Dodaj" },
    { key: "service", value: "Usluga" },
    { key: "priceUnit", value: "Valuta" },
    { key: "defaultPackagePrice", value: "Prilagođena cijena" },
    { key: "calculationMeasurement", value: "Obračunsko razdoblje za izračun" },
    { key: "alreadyAdded", value: "Stavka je već dodana!" },
    { key: "servicesManagement", value: "Upravljanje uslugama" },
    { key: "servicesSingle", value: "Pojedinačne usluge" },
    { key: "serviceSingle", value: "Pojedinačna usluga" },
    { key: "packages", value: "Paketi usluga" },
    { key: "discounts", value: "Popusti" },
    { key: "servicesManagementSingle", value: "Simulacija ponude" },
    { key: "defaultPrice", value: "Fiksna cijena" },
    { key: "packagePriceCalculated", value: "Izračunata cijena" },
    { key: "defaultNumberOfUnits", value: "Fiksna količina jedinica" },
    { key: "defaultNumberOfUnitsInfo", value: "Kada koristite fiksnu količinu jedinica pri dodavanju usluge u paket, koristi se uneseni broj jedinica i obračunava na temelju unesene cijene po jedinici. Količinu nije moguće mijenjati prilikom dodavanja stavke u obračun." },
    { key: "deactivateService", value: "Želite li ukloniti uslugu iz ponude?" },
    { key: "sum", value: "Ukupan iznos" },
    { key: "noData", value: "Nema podataka za prikaz!" },
    { key: "deactivatePackage", value: "Želite li ukloniti paket usluga iz ponude?" },
    { key: "accomodationManagementRoom", value: "Razmještaj po sobama" },
    { key: "percentCalculation", value: "Postotni izračun" },
    { key: "discountsManagement", value: "Upravljanje popustima" },
    { key: "deactivateDiscount", value: "Želite li deaktivirati popust?" },
    { key: "notifications", value: "Obavijesti" },
    { key: "markAllAsRead", value: "Označi sve kao pročitano" },
    { key: "showAll", value: "Sve obavijesti" },
    { key: "all", value: "Sve" },
    { key: "events", value: "Događaji" },
    { key: "reminders", value: "Podsjetnici" },
    { key: "settings", value: "Postavke" },
    { key: "personsManagement", value: "Upravljanje osobama" },
    { key: "markAsRead", value: "Označi kao pročitano" },
    { key: "goToNotification", value: "Idi na obavijest" },
    { key: "servicesOnly", value: "Usluge" },
    { key: "packagesOnly", value: "Paketi" },
    { key: "new", value: "Novo" },
    { key: "showDetails", value: "Prikaži detalje" },
    { key: "offerDate", value: "Datum ponude" },
    { key: "offerItems", value: "Stavke ponude" },
    { key: "offerDragAndDrop", value: "Povucite stavke iz lijevog panela ovdje" },
    { key: "clearAll", value: "Očisti sve" },
    { key: "transactionDate", value: "Datum transakcije" },
    { key: "logType", value: "Vrsta radnje" },
    { key: "activeRoom", value: "Trenutni smještaj" },
    { key: "roomStartDate", value: "Početak boravka" },
    { key: "roomEndDate", value: "Završetak boravka" },
    { key: "addDiscount", value: "Dodaj popust" },
    { key: "selected", value: "Odabrano" },
    { key: "markSelectedAsRead", value: "Označi odabrano kao pročitano" },
    { key: "selectAll", value: "Označi sve" },
    { key: "offerPrint", value: "P O N U D A" },
    { key: "thankYou", value: "Hvala na povjerenju!" },
    { key: "nothingToPrint", value: "Nema podataka za ispis!" },
    { key: "offerFor", value: "Ponuda za" },
    { key: "offerPackagesForPerson", value: "Paket usluga za novu osobu" },
    { key: "offerPersonStepText", value: "Ovdje možete odabrati pakete usluga za novu osobu. Paket i usluge možete dodati i naknadno na portalu za pregled podataka o osobi. Odabrane pakete i usluge možete poslije izmijeniti. Nakon odabira ponude nemojte zaboraviti spremiti podatke!" },
    { key: "createOffer", value: "Kreiraj ponudu" },
    { key: "addNewData", value: "Dodaj novo" },
    { key: "fileNotFound", value: "Datoteka nije pronađena u memoriji!" },
    { key: "downloadStartSoon", value: "Datoteka će se uskoro preuzeti." },
    { key: "addDocument", value: "Novi dokument" },
    { key: "documentType", value: "Vrsta dokumenta" },
    { key: "fileType", value: "Vrsta datoteke" },
    { key: "uploadDate", value: "Datum učitavanja" },
    { key: "wantToDelete", value: "Sigurno želiš obrisati?" },
    { key: "wantToSaveOffer", value: "Sigurno želiš spremiti promjene u paketu usluga?" },
    { key: "markNoteAsFavorite", value: "Dodaj bilješku u favorite" },
    { key: "removeNoteFromFavorites", value: "Ukloni bilješku iz favorita" },
    { key: "tagsManagement", value: "Upravljanje oznakama" },
    { key: "documentsManagement", value: "Upravljanje priloženim dokumentima" },
    { key: "deleteData", value: "Brisanje podataka" },
    { key: "documentsPersonData", value: "Dodavanje dokumenata" },
    { key: "select", value: "Odaberi" },
    { key: "notesPersonData", value: "Bilješke za novu osobu" },
    { key: "filters", value: "Filtri" },
    { key: "other", value: "Ostalo" },
    { key: "unread", value: "Nepročitano" },
    { key: "manageNotifications", value: "Upravljanje obavijestima" },
    { key: "reminder", value: "Podsjetnik" },
    { key: "daysBefore", value: "dana prije za vrstu obavijesti: " },
    { key: "smTableOrdNumber", value: "Redni broj" },
    { key: "yesBtnText", value: "da" },
    { key: "noBtnText", value: "ne" },
    { key: "contactsForPerson", value: "Kontakti osobe: " },
    { key: "calendar", value: "Kalendar" },
    { key: "addEvent", value: "Novi događaj" },
    { key: "editEvent", value: "Uređivanje događaja" },
    { key: "eventsManagement", value: "Upravljanje događajima" },
    { key: "oneDayEvent", value: "Jednodnevni događaj" },
    { key: "multipleDayEvent", value: "Višednevni događaj" },
    { key: "eventDate", value: "Datum" },
    { key: "eventStartDate", value: "Datum početka" },
    { key: "eventEndDate", value: "Datum završetka" },
    { key: "color", value: "Boja" },
    { key: "recurringEvent", value: "Ponavljaj događaj godišnje" },
    { key: "eventReminder", value: "Podsjetnik na događaj" },
    { key: "fastActions", value: "Brze akcije" },
    { key: "title", value: "Naslov" },
    { key: "typeText", value: "Unesite tekst" },
    { key: "notProvided", value: "Nije uneseno" },
    { key: "inProgress", value: "U tijeku" },
    { key: "provided", value: "Uneseno" },
    { key: "doctorVisit", value: "Liječnička posjeta za dan: " },
    { key: "startDoctorVisit", value: "Pokretanje akcije liječničkog obilaska za sve aktivne osobe" },
    { key: "delete", value: "Obriši" },
    { key: "completed", value: "Dovršeno" },
    { key: "completed", value: "Dovršeno" },
    { key: "documentsPersonStepText", value: "Ovdje možeš dodati neke dokumente vezane uz novu osobu (kopije osobnih dokumenata, upute za davanje lijekova, liječničke nalaze i slično). Dodane dokumente možeš kasnije pregledati i uređivati unutar profila osobe. Dokumente ne moraš dodati odmah..." },
    { key: "uploadDocument", value: "Dodaj dokument" },
    { key: "startCalculation", value: "Pokretanje obračuna za sve aktivne osobe" },
    { key: "calculationPage", value: "Obračun" },
    { key: "calculationFor", value: "Obračun za" },
    { key: "newCalculation", value: "Novi obračun" },
    { key: "startingCalculation", value: "Pokretanje obračuna za sve aktivne osobe" },
    { key: "daysForPayment", value: "Rok za uplatu (dani)" },
    { key: "recalculateForExisting", value: "Preračunaj za osobe koje već imaju obračun u odabranom razdoblju" },
    { key: "skipExisting", value: "Kreiraj obračun samo za osobe koje nemaju obračun u odabranom razdoblju" },
    { key: "start", value: "Pokreni" },
    { key: "calculationInProgress", value: "Kalkulacija je u tijeku, molimo pričekajte (može potrajati nekoliko minuta)" },
    { key: "invoice", value: "R A Č U N" },
    { key: "invoiceForMonth", value: "Račun za mjesec" },
    { key: "generatedDate", value: "Generirano dana" },
    { key: "invoicePeriod", value: "Razdoblje: " },
    { key: "invoiceGenerated", value: "Napomena: Ovaj dokument automatski je generiran iz sustava i može se razlikovati od stvarnog stanja!" },
    { key: "calculationDate", value: "Datum obračuna" },
    { key: "status", value: "Status" },
    { key: "systemPrice", value: "Izračunati iznos" },
    { key: "realPrice", value: "Stvarni iznos" },
    { key: "paidPrice", value: "Plaćeni iznos" },
    { key: "paidDate", value: "Datum uplate" },
    { key: "calculationNotPaid", value: "Nije plaćeno" },
    { key: "calculationPaid", value: "Plaćeno" },
    { key: "calculationCancelled", value: "Stornirano" },
    { key: "calculationSuccess", value: "Obračun uspješno kreiran" },
    { key: "chartCalculated", value: "Obračunato" },
    { key: "calculatedSumReal", value: "Ukupni stvarni iznos" },
    { key: "calculatedSumPaid", value: "Ukupni plaćeni iznos" },
    { key: "calculatedSum", value: "Ukupni izračunati iznos" },
    { key: "summaryDetails", value: "Otvori detalje" },
    { key: "person", value: "osoba" },
    { key: "calculatedFrom", value: "obračunato od" },
    { key: "actions", value: "Akcije" },
    { key: "newCalculation", value: "Novi obračun" },
    { key: "recalculateSelected", value: "Preračunaj za odabrane" },
    { key: "markRealPrice", value: "Unesi izračunati iznos kao stvarni za odabrane" },
    { key: "markPaidPrice", value: "Provedi plaćanje za odabrane" },
    { key: "cancelSelected", value: "Storniraj plaćanje za odabrane" },
    { key: "nothingSelected", value: "Nema odabranih redaka" },
    { key: "wantToMarkRealPrice", value: "Želite li unijeti izračunati iznos kao stvarni iznos za odabrane obračune?" },
    { key: "wantToMarkPaid", value: "Želite li označiti odabrane obračune kao plaćene? Unijet će se stvarni iznos kao plaćeni, ako stvarni iznos nije unsen iskoristit će se izračunati iznos. Datum plaćanja će biti trenutni datum." },
    { key: "wantToCancelSelected", value: "Želite li stornirati plaćanje obračuna? Stornirani obračuni ne ulaze u računanje ukupnih iznosa." },
    { key: "calculationSummary", value: "Detalji obračuna" },
    { key: "month", value: "mjesec" },
    { key: "period", value: "Razdoblje" },
    { key: "calculationNumber", value: "Broj obračuna" },
    { key: "numberOfPersons", value: "Ukupan broj aktivnih osoba" },
    { key: "calculationCreatedFor", value: "Obračun kreiran za" },
    { key: "calculationSystemPrice", value: "Izračunati iznos" },
    { key: "lastMonth", value: "u odnosu na prošli mjesec" },
    { key: "calculationRealPrice", value: "Stvarni iznos" },
    { key: "calculationPaidPrice", value: "Plaćeni iznos" },
    { key: "calculationCancelled", value: "Stornirani obračuni" },
    { key: "cancelledCalculationsDescription", value: "Stornirani obračuni izuzeti su iz ukupnog izračunatog, stvarnog i plaćenog iznosa." },
    { key: "numberOfCancelledCalculations", value: "Broj storniranih obračuna" },
    { key: "enterRealPrice", value: "Unesi stvarnu cijenu" },
    { key: "enterPaidPrice", value: "Unesi podatke o plaćanju" },
    { key: "cancelCalculation", value: "Storniraj obračun" },
    { key: "calculationDocuments", value: "Pregledaj dokumente vezane uz obračun" },
    { key: "wantToCancelCalculation", value: "Sigurno želiš stornirati obračun? Nakon storniranja obračun više ne ulazi u izračun ukupnog iznosa." },
    { key: "realPriceModalTitle", value: "Unos stvarne cijene" },
    { key: "paidPriceModalTitle", value: "Plaćanje obračuna" },
    { key: "personCalculation", value: "Računi" },
    { key: "calculationMonth", value: "Mjesec" },
    { key: "calculationYear", value: "Godina" },
    { key: "doctorVisitAction", value: "Liječnički obilazak" },
    { key: "startCalculationAction", value: "Brzi obračun" },
    { key: "calculationInfoPopover", value: "Ukoliko paket ima unesenu prilagođenu cijenu, konačna cijena paketa je jednaka prilagođenoj cijeni. Ukoliko paket ima izračunatu cijenu, cijena se računa temeljem usluga koje obuhvaća paket (uporabom cijena i količina usluga)." },
    { key: "download", value: "Preuzimanje" },
];

const map = new Map(strings.map(obj => [obj.key, obj.value]));