export interface IKeyValue {
    key: string;
    value: string;
}

export function getString(key: string): string {
    return map.get(key) || key;
}

const strings: IKeyValue[] = [
    { key: "dashboard", value: "Početna" },
    { key: "roomManagement", value: "Upravljanje sobama" },
    { key: "floors", value: "Katevi" },
    { key: "rooms", value: "Sobe" },
    { key: "id", value: "Šifra" },
    { key: "name", value: "Naziv" },
    { key: "capacity", value: "Kapacitet" },
    { key: "floor", value: "Kat" },
    { key: "saveSuccess", value: "Uspješno spremljeno!" },
    { key: "saveError", value: "Pogreška prilikom spremanja!" },
    { key: "noRoomsForSelectedFloor", value: "Nema spremljenih soba za odabrani kat!" },
    { key: "persons", value: "Osobe" },
    { key: "basicData", value: "Osnovni podaci" },
    { key: "firstName", value: "Ime" },
    { key: "lastName", value: "Prezime" },
    { key: "jmbg", value: "JMBG" },
    { key: "birthDate", value: "Datum rođenja" },
    { key: "stayData", value: "Podaci o boravku" },
    { key: "startDate", value: "Datum dolaska" },
    { key: "endDate", value: "Datum odlaska" },
    { key: "creationDate", value: "Datum unosa" },
    { key: "currentStatus", value: "Trenutni status osobe" },
    { key: "active", value: "Aktivan" },
    { key: "unactive", value: "Neaktivan" },
    { key: "activeTooltip", value: "Osoba je trenutno smještena u ustanovi." },
    { key: "unactiveTooltip", value: "Osoba je bila smještena u ustanovi, ali je njen boravak završio." },
    { key: "deactivatePerson", value: "Deaktiviraj osobu" },
    { key: "dormatoryData", value: "Podaci o smještaju" },
    { key: "currentFloor", value: "Kat na kojemu je osoba smještena" },
    { key: "room", value: "Soba" },
    { key: "goToExternalRoomManagement", value: "Idi na vanjsko upravljanje smještajem" },
    { key: "goToAdvancedEdit", value: "Idi na napredno uređivanje" },
    { key: "save", value: "Spremi" },
    { key: "cancel", value: "Odustani" },
    { key: "personData", value: "Podaci o osobi" },
    { key: "activePersonDetails", value: "Aktivna osoba je osoba koja je trenutno smještena u ustanovi." },
    { key: "unactivePersonDetails", value: "Neaktivna osoba je osoba čiji je boravak u ustanovi završio." },
    { key: "changeStatusPersonText1", value: "Za prebacivanje osobe iz statusa aktivne u neaktivnu potrebno je kliknuti gumb: " },
    { key: "changeStatusPersonText2", value: "Ukoliko ne navedete 'Datum odlaska' spremit će se trenutni datum kao datum odlaska osobe iz ustanove." },
    { key: "unactivePersons", value: "Prikaži neaktivne osobe" },
    { key: "areYouSure", value: "Jeste li sigurni?" },
    { key: "questionDeactivatePerson", value: "Želite li deaktivirati osobu s datumom: " },
    { key: "yes", value: "Da" },
    { key: "no", value: "Ne" },
    { key: "search", value: "Pretraživanje" },
    { key: "contacts", value: "Kontakti" },
    { key: "email", value: "E-mail" },
    { key: "telephone", value: "Telefon" },
    { key: "mobile", value: "Mobitel" },
    { key: "noContacts", value: "Nema spremljenih kontakata!" },
    { key: "addPerson", value: "Unos nove osobe" },
    { key: "basicPersonData", value: "Osnovni podaci o osobi" },
    { key: "basicPersonStepText", value: "Ovdje popunite osnovne podatke o novoj osobi. Nakon unosa, klikom na gumb za dodavanje nove osobe, osoba je dodana u sustav. U daljnim koracima možete (ne morate) popuniti neke dodatne podatke o novom korisniku doma, na primjer: unijeti kontakt osobe, dodijeliti sobu za smještaj, bilješke, dokumente i slično." },
    { key: "saveNewPerson", value: "Spremi novu osobu" },
    { key: "back", value: "Nazad" },
    { key: "next", value: "Dalje" },
    { key: "required", value: "Polje je obavezno!" },
    { key: "contactsPersonData", value: "Kontakt osobe" },
    { key: "contactsPersonStepText", value: "Ovdje popunite podatke o kontakt osobama. Možete navesti više kontakt osoba, te za svaku osobu popuniti neku vrstu kontakta (e-mail, telefonski broj ili mobilni broj). Za svaki kontakt obavezno je unijeti ime i prezime." },
    { key: "accomodation", value: "Smještaj" },
    { key: "documents", value: "Dokumenti" },
    { key: "notes", value: "Bilješke" },
    { key: "services", value: "Paket usluga" },
    { key: "savePersonFirst", value: "Za unos prvo spremite osnovne podatke o osobi!" },
    { key: "accomodationPersonStepText", value: "Ovdje popunite podatke o smještaju nove osobe. Osobu možete smjestiti samo u sobu u kojoj ima slobodnog mjesta. U jednoj sobi mogu biti smještene samo osobe istoga spola (obratite pažnju ukoliko već imate osobu u odabranoj sobi!). Podatke možete uređivati i sa portala za upravljanje smještajem." },
    { key: "address", value: "Adresa" },
    { key: "gender", value: "Spol" },
    { key: "savePersonFirst", value: "Za unos prvo spremite osnovne podatke o osobi!" },
];

const map = new Map(strings.map(obj => [obj.key, obj.value]));