CREATE TABLE [dbo].[Log](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LogTypeId] [int] NOT NULL,
	[LogEntityId] [int] NOT NULL,
	[KeyId] [int] NOT NULL,
	[UserId] [char](36) NULL,
	[CreationDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Log] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
 

ALTER TABLE [dbo].[Log]  WITH CHECK ADD  CONSTRAINT [FK_Log_LogEntity] FOREIGN KEY([LogEntityId])
REFERENCES [dbo].[LogEntity] ([Id])
 

ALTER TABLE [dbo].[Log] CHECK CONSTRAINT [FK_Log_LogEntity]
 

ALTER TABLE [dbo].[Log]  WITH CHECK ADD  CONSTRAINT [FK_Log_LogType] FOREIGN KEY([LogTypeId])
REFERENCES [dbo].[LogType] ([Id])
 

ALTER TABLE [dbo].[Log] CHECK CONSTRAINT [FK_Log_LogType]
 

