USE [ENV01_NURSING_HOME]
GO

/****** Object:  Table [dbo].[Log]    Script Date: 28.4.2023. 12:06:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Log](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LogTypeId] [int] NOT NULL,
	[LogEntityId] [int] NOT NULL,
	[KeyId] [int] NOT NULL,
	[CreationDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Log] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Log]  WITH CHECK ADD  CONSTRAINT [FK_Log_LogEntity] FOREIGN KEY([LogEntityId])
REFERENCES [dbo].[LogEntity] ([Id])
GO

ALTER TABLE [dbo].[Log] CHECK CONSTRAINT [FK_Log_LogEntity]
GO

ALTER TABLE [dbo].[Log]  WITH CHECK ADD  CONSTRAINT [FK_Log_LogType] FOREIGN KEY([LogTypeId])
REFERENCES [dbo].[LogType] ([Id])
GO

ALTER TABLE [dbo].[Log] CHECK CONSTRAINT [FK_Log_LogType]
GO

