CREATE TABLE [dbo].[FavoriteNotes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NoteId] [int] NOT NULL,
 CONSTRAINT [PK_FavoriteNotes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
 

ALTER TABLE [dbo].[FavoriteNotes]  WITH CHECK ADD  CONSTRAINT [FK_FavoriteNotes_Note] FOREIGN KEY([NoteId])
REFERENCES [dbo].[Note] ([Id])
 

ALTER TABLE [dbo].[FavoriteNotes] CHECK CONSTRAINT [FK_FavoriteNotes_Note]
 

