USE [master]
GO

/****** Object:  Database [ENV01_NURSING_HOME]    Script Date: 13.4.2023. 15:16:08 ******/
CREATE DATABASE [ENV01_NURSING_HOME]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ENV01_NURSING_HOME', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ENV01_NURSING_HOME.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ENV01_NURSING_HOME_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ENV01_NURSING_HOME_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ENV01_NURSING_HOME].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET ARITHABORT OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET RECOVERY FULL 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET  MULTI_USER 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ENV01_NURSING_HOME] SET  READ_WRITE 
GO

