INSERT INTO [dbo].[Permission] ([Name], [Description]) VALUES
('VIEW_DASHBOARD',       'Access to dashboard overview'),
('VIEW_USERS',           'View user list'),
('ADD_USERS',            'Create new users'),
('EDIT_USERS',           'Edit user data'),
('DELETE_USERS',         'Delete users'),
('MANAGE_USERS',         'Block, unblock, activate, deactivate and send verification emails to users'),
('VIEW_PERSONS',         'View residents'),
('ADD_PERSONS',          'Add new residents'),
('EDIT_PERSONS',         'Edit resident data'),
('DELETE_PERSONS',       'Delete residents'),
('VIEW_NOTES',           'View notes'),
('ADD_NOTES',            'Add notes'),
('EDIT_NOTES',           'Edit notes'),
('DELETE_NOTES',         'Delete notes'),
('VIEW_DOCUMENTS',       'View documents'),
('ADD_DOCUMENTS',        'Upload documents'),
('VIEW_CALCULATIONS',    'View financial calculations'),
('MANAGE_CALCULATIONS',  'Create and manage financial calculations'),
('VIEW_EMPLOYEES',       'View employee list'),
('ADD_EMPLOYEES',        'Add new employees'),
('EDIT_EMPLOYEES',       'Edit employee data'),
('VIEW_CALENDAR',        'View calendar events'),
('MANAGE_CALENDAR',      'Create and manage calendar events'),
('VIEW_SERVICES',        'View services list'),
('MANAGE_SERVICES',      'Create and manage services'),
('VIEW_PACKAGES',        'View packages list'),
('MANAGE_PACKAGES',      'Create and manage packages'),
('VIEW_NOTIFICATIONS',   'View notifications'),
('VIEW_SETTINGS',        'View application settings'),
('MANAGE_SETTINGS',      'Manage application settings'),
('VIEW_FURNITURE',       'View furniture inventory'),
('MANAGE_FURNITURE',     'Manage furniture inventory');
