INSERT INTO [dbo].[Country]
           ([Name])
     VALUES
('Bosna i Hercegovina'), 
('Hrvatska'),    
('Afganistan'),
('Albanija'),
('Alžir'),
('Andora'),
('Angola'),
('Antigva i Barbuda'),
('Argentina'),
('Armenija'),
('Australija'),
('Austrija'),
('Azerbajdžan'),
('Bahami'),
('Bahrein'),
('Bangladeš'),
('Barbados'),
('Bjelorusija'),
('Belgija'),
('Belize'),
('Benin'),
('Butan'),
('Bolivija'),
('Bocvana'),
('Brazil'),
('Brunej'),
('Bugarska'),
('Burkina Faso'),
('Burundi'),
('Zeleni Rt'),
('Kambodža'),
('Kamerun'),
('Kanada'),
('Centralnoafrička Republika'),
('Čad'),
('Čile'),
('Kina'),
('Kolumbija'),
('Komori'),
('Kongo'),
('Kostarika'),
('Kuba'),
('Cipar'),
('Češka'),
('Danska'),
('Džibuti'),
('Dominika'),
('Dominikanska Republika'),
('Istočni Timor (Timor-Leste)'),
('Ekvador'),
('Egipat'),
('Salvador'),
('Ekvatorska Gvineja'),
('Eritreja'),
('Estonija'),
('Esvatini'),
('Etiopija'),
('Fidži'),
('Finska'),
('Francuska'),
('Gabon'),
('Gambia'),
('Gruzija'),
('Njemačka'),
('Gana'),
('Grčka'),
('Grenada'),
('Gvatemala'),
('Gvineja'),
('Gvineja-Bissau'),
('Gvajana'),
('Haiti'),
('Honduras'),
('Mađarska'),
('Island'),
('Indija'),
('Indonezija'),
('Iran'),
('Irak'),
('Irska'),
('Izrael'),
('Italija'),
('Jamajka'),
('Japan'),
('Jordan'),
('Kazahstan'),
('Kenija'),
('Kiribati'),
('Sjeverna Koreja'),
('Južna Koreja'),
('Kosovo'),
('Kuvajt'),
('Kirgistan'),
('Laos'),
('Latvija'),
('Libanon'),
('Lesoto'),
('Liberija'),
('Libija'),
('Lihtenštajn'),
('Litva'),
('Luksemburg'),
('Madagaskar'),
('Malavi'),
('Malezija'),
('Maldivi'),
('Mali'),
('Malta'),
('Maršalovi Otoci'),
('Mauritanija'),
('Mauricijus'),
('Meksiko'),
('Mikronezija'),
('Moldavija'),
('Monako'),
('Mongolija'),
('Crna Gora'),
('Maroko'),
('Mozambik'),
('Mjanmar (Burma)'),
('Namibija'),
('Nauru'),
('Nepal'),
('Nizozemska'),
('Novi Zeland'),
('Nikaragva'),
('Niger'),
('Nigerija'),
('Sjeverna Makedonija'),
('Norveška'),
('Oman'),
('Pakistan'),
('Palau'),
('Panama'),
('Papua Nova Gvineja'),
('Paragvaj'),
('Peru'),
('Filipini'),
('Poljska'),
('Portugal'),
('Katar'),
('Rumunjska'),
('Rusija'),
('Ruanda'),
('Sveti Kristofor i Nevis'),
('Sveta Lucija'),
('Sveti Vincent i Grenadini'),
('Samoa'),
('San Marino'),
('Sao Tome i Principe'),
('Saudijska Arabija'),
('Senegal'),
('Srbija'),
('Sejšeli'),
('Sijera Leone'),
('Singapur'),
('Slovačka'),
('Slovenija'),
('Solomonski Otoci'),
('Somalija'),
('Južna Afrika'),
('Južni Sudan'),
('Španjolska'),
('Šri Lanka'),
('Sudan'),
('Surinam'),
('Švedska'),
('Švicarska'),
('Sirija'),
('Tajvan'),
('Tadžikistan'),
('Tanzanija'),
('Tajland'),
('Togo'),
('Tonga'),
('Trinidad i Tobago'),
('Tunis'),
('Turska'),
('Turkmenistan'),
('Tuvalu'),
('Uganda'),
('Ukrajina'),
('Ujedinjeni Arapski Emirati'),
('Ujedinjeno Kraljevstvo'),
('Sjedinjene Američke Države'),
('Urugvaj'),
('Uzbekistan'),
('Vanuatu'),
('Vatikan'),
('Venecuela'),
('Vijetnam'),
('Jemen'),
('Zambija'),
('Zimbabve');