-- Persons 1-15
EXEC insertPerson @FirstName='Mariel', @LastName='Swancott', @JMBG='0583453890699', @BirthDate='1956-10-31', @StartDate='2023-10-22', @GenderId=2, @FatherFirstName='Morty', @MotherFirstName='Lisette', @MotherMaidenLastName='Sproule', @BirthCityId=14, @BirthCountryId=1, @ResidanceCityId=15, @ResidanceStreetName='Bunting', @ResidanceHouseNumber='69', @Telephone='(275) 3052453', @DoctorName='Morty Sproule';
EXEC insertPerson @FirstName='Lane', @LastName='Brooksbie', @JMBG='3673278721032', @BirthDate='1947-04-10', @StartDate='2024-04-23', @GenderId=2, @FatherFirstName='Noby', @MotherFirstName='Claudette', @MotherMaidenLastName='Deboy', @BirthCityId=14, @BirthCountryId=1, @ResidanceCityId=14, @ResidanceStreetName='Reindahl', @ResidanceHouseNumber='49', @Telephone='(815) 2708388', @DoctorName='Noby Deboy';
EXEC insertPerson @FirstName='Elvis', @LastName='Ostick', @JMBG='4349337419460', @BirthDate='1967-08-22', @StartDate='2023-04-11', @GenderId=1, @FatherFirstName='Rabi', @MotherFirstName='Lin', @MotherMaidenLastName='Gehricke', @BirthCityId=3, @BirthCountryId=1, @ResidanceCityId=14, @ResidanceStreetName='Kingsford', @ResidanceHouseNumber='300', @Telephone='(185) 2807029', @DoctorName='Rabi Gehricke';
EXEC insertPerson @FirstName='Cale', @LastName='Kose', @JMBG='8591939302529', @BirthDate='1949-11-17', @StartDate='2024-02-03', @GenderId=2, @FatherFirstName='Erie', @MotherFirstName='Pat', @MotherMaidenLastName='Tunmore', @BirthCityId=21, @BirthCountryId=1, @ResidanceCityId=32, @ResidanceStreetName='Longview', @ResidanceHouseNumber='8776', @Telephone=NULL, @DoctorName='Erie Tunmore';
EXEC insertPerson @FirstName='Claiborn', @LastName='Linnett', @JMBG='0768596070035', @BirthDate='1950-04-25', @StartDate='2023-09-17', @GenderId=2, @FatherFirstName='Shepard', @MotherFirstName='Tildie', @MotherMaidenLastName='Breedy', @BirthCityId=24, @BirthCountryId=1, @ResidanceCityId=45, @ResidanceStreetName='Armistice', @ResidanceHouseNumber='88', @Telephone=NULL, @DoctorName='Shepard Breedy';
EXEC insertPerson @FirstName='Earvin', @LastName='Greatrex', @JMBG='1035166078464', @BirthDate='1931-02-17', @StartDate='2023-02-02', @GenderId=2, @FatherFirstName='Felizio', @MotherFirstName='Verla', @MotherMaidenLastName='Suttill', @BirthCityId=27, @BirthCountryId=1, @ResidanceCityId=25, @ResidanceStreetName='Troy', @ResidanceHouseNumber='0', @Telephone=NULL, @DoctorName='Felizio Suttill';
EXEC insertPerson @FirstName='Nerissa', @LastName='Coulman', @JMBG='3320606731727', @BirthDate='1954-03-29', @StartDate='2023-06-20', @GenderId=2, @FatherFirstName='Brade', @MotherFirstName='Nikoletta', @MotherMaidenLastName='Gerry', @BirthCityId=12, @BirthCountryId=1, @ResidanceCityId=44, @ResidanceStreetName='Morning', @ResidanceHouseNumber='9', @Telephone=NULL, @DoctorName='Brade Gerry';
EXEC insertPerson @FirstName='Leia', @LastName='Guerin', @JMBG='0274240508767', @BirthDate='1963-04-03', @StartDate='2023-10-11', @GenderId=1, @FatherFirstName='Major', @MotherFirstName='Concettina', @MotherMaidenLastName='Thresh', @BirthCityId=7, @BirthCountryId=1, @ResidanceCityId=15, @ResidanceStreetName='Riverside', @ResidanceHouseNumber='56', @Telephone=NULL, @DoctorName='Major Thresh';
EXEC insertPerson @FirstName='Giorgio', @LastName='Ganley', @JMBG='3650438612903', @BirthDate='1945-12-11', @StartDate='2023-12-02', @GenderId=2, @FatherFirstName='Isidore', @MotherFirstName='Janeva', @MotherMaidenLastName='Chinnick', @BirthCityId=7, @BirthCountryId=1, @ResidanceCityId=24, @ResidanceStreetName='Michigan', @ResidanceHouseNumber='01', @Telephone=NULL, @DoctorName='Isidore Chinnick';
EXEC insertPerson @FirstName='Coraline', @LastName='Tracy', @JMBG='2041892797675', @BirthDate='1965-01-26', @StartDate='2023-10-06', @GenderId=2, @FatherFirstName='Brewer', @MotherFirstName='Gladys', @MotherMaidenLastName='Hatherleigh', @BirthCityId=17, @BirthCountryId=1, @ResidanceCityId=50, @ResidanceStreetName='2nd', @ResidanceHouseNumber='1', @Telephone=NULL, @DoctorName='Brewer Hatherleigh';
EXEC insertPerson @FirstName='Saree', @LastName='Luggar', @JMBG='6458704564563', @BirthDate='1954-08-29', @StartDate='2023-05-08', @GenderId=1, @FatherFirstName='Terencio', @MotherFirstName='Quentin', @MotherMaidenLastName='Saville', @BirthCityId=26, @BirthCountryId=1, @ResidanceCityId=33, @ResidanceStreetName='Boyd', @ResidanceHouseNumber='48666', @Telephone=NULL, @DoctorName='Terencio Saville';
EXEC insertPerson @FirstName='Conney', @LastName='Simanenko', @JMBG='7916255707205', @BirthDate='1940-09-12', @StartDate='2023-05-28', @GenderId=2, @FatherFirstName='Haywood', @MotherFirstName='Tiffi', @MotherMaidenLastName='Brooker', @BirthCityId=41, @BirthCountryId=1, @ResidanceCityId=37, @ResidanceStreetName='Browning', @ResidanceHouseNumber='0588', @Telephone=NULL, @DoctorName='Haywood Brooker';
EXEC insertPerson @FirstName='Verena', @LastName='Stoffer', @JMBG='4071892912998', @BirthDate='1937-12-29', @StartDate='2024-01-24', @GenderId=1, @FatherFirstName='Andonis', @MotherFirstName='Rosette', @MotherMaidenLastName='Woollett', @BirthCityId=46, @BirthCountryId=1, @ResidanceCityId=49, @ResidanceStreetName='Dottie', @ResidanceHouseNumber='1698', @Telephone=NULL, @DoctorName='Andonis Woollett';
EXEC insertPerson @FirstName='Jules', @LastName='Toderi', @JMBG='9143217605659', @BirthDate='1945-10-10', @StartDate='2023-05-19', @GenderId=2, @FatherFirstName='Gabbie', @MotherFirstName='Rora', @MotherMaidenLastName='Valance', @BirthCityId=50, @BirthCountryId=1, @ResidanceCityId=16, @ResidanceStreetName='Transport', @ResidanceHouseNumber='72', @Telephone=NULL, @DoctorName='Gabbie Valance';
EXEC insertPerson @FirstName='Erin', @LastName='Dabnot', @JMBG='4497079327660', @BirthDate='1931-10-03', @StartDate='2023-05-30', @GenderId=1, @FatherFirstName='Neron', @MotherFirstName='Dredi', @MotherMaidenLastName='Rodie', @BirthCityId=1, @BirthCountryId=1, @ResidanceCityId=46, @ResidanceStreetName='Quincy', @ResidanceHouseNumber='18', @Telephone=NULL, @DoctorName='Neron Rodie';

-- Health conditions for persons 
EXEC insertHealthConditionForPerson  @PersonId = 1, @HealthConditionId = 2;
EXEC insertHealthConditionForPerson  @PersonId = 1, @HealthConditionId = 5;
EXEC insertHealthConditionForPerson  @PersonId = 2, @HealthConditionId = 1;
EXEC insertHealthConditionForPerson  @PersonId = 2, @HealthConditionId = 7;
EXEC insertHealthConditionForPerson  @PersonId = 3, @HealthConditionId = 8, @Description=N'Health condition';
EXEC insertHealthConditionForPerson  @PersonId = 4, @HealthConditionId = 2;
EXEC insertHealthConditionForPerson  @PersonId = 5, @HealthConditionId = 2;
EXEC insertHealthConditionForPerson  @PersonId = 6, @HealthConditionId = 2;
EXEC insertHealthConditionForPerson  @PersonId = 7, @HealthConditionId = 2;
EXEC insertHealthConditionForPerson  @PersonId = 8, @HealthConditionId = 2;
EXEC insertHealthConditionForPerson  @PersonId = 9, @HealthConditionId = 2;
EXEC insertHealthConditionForPerson  @PersonId = 10, @HealthConditionId = 2;
EXEC insertHealthConditionForPerson  @PersonId = 11, @HealthConditionId = 2;
EXEC insertHealthConditionForPerson  @PersonId = 12, @HealthConditionId = 2;
EXEC insertHealthConditionForPerson  @PersonId = 13, @HealthConditionId = 2;
EXEC insertHealthConditionForPerson  @PersonId = 14, @HealthConditionId = 2;
EXEC insertHealthConditionForPerson  @PersonId = 15, @HealthConditionId = 2;

-- Category for persons
EXEC insertCategoryForPerson  @PersonId = 1, @CategoryId = 2;
EXEC insertCategoryForPerson  @PersonId = 2, @CategoryId = 3;
EXEC insertCategoryForPerson  @PersonId = 3, @CategoryId = 4;
EXEC insertCategoryForPerson  @PersonId = 4, @CategoryId = 1;
EXEC insertCategoryForPerson  @PersonId = 5, @CategoryId = 1;
EXEC insertCategoryForPerson  @PersonId = 6, @CategoryId = 1;
EXEC insertCategoryForPerson  @PersonId = 7, @CategoryId = 1;
EXEC insertCategoryForPerson  @PersonId = 8, @CategoryId = 1;
EXEC insertCategoryForPerson  @PersonId = 9, @CategoryId = 1;
EXEC insertCategoryForPerson  @PersonId = 10, @CategoryId = 1;
EXEC insertCategoryForPerson  @PersonId = 11, @CategoryId = 1;
EXEC insertCategoryForPerson  @PersonId = 12, @CategoryId = 1;
EXEC insertCategoryForPerson  @PersonId = 13, @CategoryId = 1;
EXEC insertCategoryForPerson  @PersonId = 14, @CategoryId = 1;
EXEC insertCategoryForPerson  @PersonId = 15, @CategoryId = 1;

-- Contacts
EXEC insertContact @FirstName='Rasia', @LastName='Cunniff', @JMBG='4528973776427', @ResidanceCityId=7, @ResidanceStreetName='Heath', @ResidanceHouseNumber='6383', @Telephone='(273) 5513099', @PersonId=3, @IsObligeeToPay=1, @IsGuardian=0;
EXEC insertContact @FirstName='Madelin', @LastName='Drezzer', @JMBG='0622793446670', @ResidanceCityId=25, @ResidanceStreetName='Garrison', @ResidanceHouseNumber='99', @Telephone=NULL, @PersonId=9, @IsObligeeToPay=0, @IsGuardian=0;
EXEC insertContact @FirstName='Scotty', @LastName='Ianetti', @JMBG='9209548813911', @ResidanceCityId=40, @ResidanceStreetName='Sommers', @ResidanceHouseNumber='39712', @Telephone=NULL, @PersonId=6, @IsObligeeToPay=0, @IsGuardian=0;
EXEC insertContact @FirstName='Francesco', @LastName='Beardon', @JMBG='7002273601640', @ResidanceCityId=15, @ResidanceStreetName='Erie', @ResidanceHouseNumber='626', @Telephone=NULL, @PersonId=7, @IsObligeeToPay=1, @IsGuardian=1;
EXEC insertContact @FirstName='Lynnette', @LastName='Roslen', @JMBG='6876637647557', @ResidanceCityId=50, @ResidanceStreetName='Steensland', @ResidanceHouseNumber='630', @Telephone=NULL, @PersonId=13, @IsObligeeToPay=0, @IsGuardian=0;
EXEC insertContact @FirstName='Kylynn', @LastName='Ovize', @JMBG='2192373594640', @ResidanceCityId=19, @ResidanceStreetName='Rowland', @ResidanceHouseNumber='50', @Telephone=NULL, @PersonId=9, @IsObligeeToPay=0, @IsGuardian=1;
EXEC insertContact @FirstName='Tara', @LastName='Deares', @JMBG='2782531442484', @ResidanceCityId=46, @ResidanceStreetName='Commercial', @ResidanceHouseNumber='19703', @Telephone=NULL, @PersonId=15, @IsObligeeToPay=1, @IsGuardian=0;
EXEC insertContact @FirstName='Darby', @LastName='Ridel', @JMBG='5734745148442', @ResidanceCityId=28, @ResidanceStreetName='5th', @ResidanceHouseNumber='59736', @Telephone=NULL, @PersonId=5, @IsObligeeToPay=1, @IsGuardian=1;
EXEC insertContact @FirstName='Aylmer', @LastName='Charrington', @JMBG='5654580502757', @ResidanceCityId=39, @ResidanceStreetName='Washington', @ResidanceHouseNumber='3', @Telephone=NULL, @PersonId=8, @IsObligeeToPay=0, @IsGuardian=0;
EXEC insertContact @FirstName='Letizia', @LastName='Cornell', @JMBG='1468616098762', @ResidanceCityId=30, @ResidanceStreetName='Fallview', @ResidanceHouseNumber='60', @Telephone=NULL, @PersonId=2, @IsObligeeToPay=0, @IsGuardian=1;
EXEC insertContact @FirstName='Solly', @LastName='MacDearmid', @JMBG='2720171745758', @ResidanceCityId=30, @ResidanceStreetName='Cascade', @ResidanceHouseNumber='60444', @Telephone='(965) 7351860', @PersonId=8, @IsObligeeToPay=1, @IsGuardian=1;
EXEC insertContact @FirstName='Tabby', @LastName='Wallenger', @JMBG='1376375683077', @ResidanceCityId=34, @ResidanceStreetName='John Wall', @ResidanceHouseNumber='467', @Telephone=NULL, @PersonId=10, @IsObligeeToPay=1, @IsGuardian=1;
EXEC insertContact @FirstName='Lorenza', @LastName='Micheu', @JMBG='8417259852225', @ResidanceCityId=29, @ResidanceStreetName='Prentice', @ResidanceHouseNumber='050', @Telephone=NULL, @PersonId=3, @IsObligeeToPay=1, @IsGuardian=1;
EXEC insertContact @FirstName='Florrie', @LastName='Diboll', @JMBG='3786906285678', @ResidanceCityId=6, @ResidanceStreetName='Rusk', @ResidanceHouseNumber='24753', @Telephone=NULL, @PersonId=10, @IsObligeeToPay=0, @IsGuardian=0;
EXEC insertContact @FirstName='Mellisa', @LastName='Lester', @JMBG='1783733537525', @ResidanceCityId=14, @ResidanceStreetName='6th', @ResidanceHouseNumber='9', @Telephone=NULL, @PersonId=2, @IsObligeeToPay=0, @IsGuardian=1;
EXEC insertContact @FirstName='Cecily', @LastName='Mertsching', @JMBG='1778455972675', @ResidanceCityId=45, @ResidanceStreetName='Grasskamp', @ResidanceHouseNumber='3', @Telephone='(647) 3102608', @PersonId=8, @IsObligeeToPay=0, @IsGuardian=1;
EXEC insertContact @FirstName='Rickie', @LastName='Strawbridge', @JMBG='5385601484390', @ResidanceCityId=47, @ResidanceStreetName='Garrison', @ResidanceHouseNumber='48', @Telephone=NULL, @PersonId=12, @IsObligeeToPay=0, @IsGuardian=1;
EXEC insertContact @FirstName='Georg', @LastName='Iuorio', @JMBG='3995163904977', @ResidanceCityId=35, @ResidanceStreetName='Mendota', @ResidanceHouseNumber='6', @Telephone=NULL, @PersonId=11, @IsObligeeToPay=0, @IsGuardian=0;
EXEC insertContact @FirstName='Abraham', @LastName='Boc', @JMBG='0312139822985', @ResidanceCityId=28, @ResidanceStreetName='Rowland', @ResidanceHouseNumber='0', @Telephone=NULL, @PersonId=13, @IsObligeeToPay=1, @IsGuardian=0;
EXEC insertContact @FirstName='Rooney', @LastName='Friel', @JMBG='7001252144954', @ResidanceCityId=21, @ResidanceStreetName='Oak', @ResidanceHouseNumber='554', @Telephone=NULL, @PersonId=3, @IsObligeeToPay=1, @IsGuardian=0;
EXEC insertContact @FirstName='Bevvy', @LastName='Korneluk', @JMBG='5353929768617', @ResidanceCityId=13, @ResidanceStreetName='Schiller', @ResidanceHouseNumber='01239', @Telephone=NULL, @PersonId=10, @IsObligeeToPay=0, @IsGuardian=1;
EXEC insertContact @FirstName='Blair', @LastName='McMonnies', @JMBG='9236775139876', @ResidanceCityId=46, @ResidanceStreetName='Hintze', @ResidanceHouseNumber='4', @Telephone=NULL, @PersonId=4, @IsObligeeToPay=0, @IsGuardian=0;
EXEC insertContact @FirstName='Sherye', @LastName='Golling', @JMBG='6556000804523', @ResidanceCityId=16, @ResidanceStreetName='Clarendon', @ResidanceHouseNumber='78773', @Telephone=NULL, @PersonId=2, @IsObligeeToPay=0, @IsGuardian=0;
EXEC insertContact @FirstName='Katerina', @LastName='Harlowe', @JMBG='6312505715939', @ResidanceCityId=11, @ResidanceStreetName='Fairview', @ResidanceHouseNumber='9898', @Telephone=NULL, @PersonId=14, @IsObligeeToPay=1, @IsGuardian=0;
EXEC insertContact @FirstName='Rosemary', @LastName='Johnsson', @JMBG='5393519439644', @ResidanceCityId=49, @ResidanceStreetName='Shoshone', @ResidanceHouseNumber='3', @Telephone=NULL, @PersonId=5, @IsObligeeToPay=0, @IsGuardian=1;
EXEC insertContact @FirstName='Zaneta', @LastName='Beere', @JMBG='3899946907705', @ResidanceCityId=9, @ResidanceStreetName='Bayside', @ResidanceHouseNumber='7', @Telephone=NULL, @PersonId=11, @IsObligeeToPay=1, @IsGuardian=0;
EXEC insertContact @FirstName='Corabella', @LastName='Tirone', @JMBG='1015607889725', @ResidanceCityId=5, @ResidanceStreetName='Westend', @ResidanceHouseNumber='4752', @Telephone='(120) 1245665', @PersonId=14, @IsObligeeToPay=1, @IsGuardian=0;
EXEC insertContact @FirstName='Anthe', @LastName='Widdop', @JMBG='4179090854116', @ResidanceCityId=37, @ResidanceStreetName='Shelley', @ResidanceHouseNumber='4', @Telephone=NULL, @PersonId=2, @IsObligeeToPay=1, @IsGuardian=0;
EXEC insertContact @FirstName='Wynn', @LastName='Conner', @JMBG='3231599504173', @ResidanceCityId=23, @ResidanceStreetName='School', @ResidanceHouseNumber='04934', @Telephone=NULL, @PersonId=15, @IsObligeeToPay=1, @IsGuardian=0;
EXEC insertContact @FirstName='Joye', @LastName='Corriea', @JMBG='0201678604858', @ResidanceCityId=26, @ResidanceStreetName='Vernon', @ResidanceHouseNumber='45', @Telephone=NULL, @PersonId=2, @IsObligeeToPay=0, @IsGuardian=1;

-- Rooms for persons
EXEC changeRoomPerson  @PersonId = 1, @RoomId = 1;
EXEC changeRoomPerson  @PersonId = 2, @RoomId = 1;
EXEC changeRoomPerson  @PersonId = 3, @RoomId = 2;
EXEC changeRoomPerson  @PersonId = 8, @RoomId = 2;
EXEC changeRoomPerson  @PersonId = 4, @RoomId = 3;
EXEC changeRoomPerson  @PersonId = 5, @RoomId = 3;
EXEC changeRoomPerson  @PersonId = 6, @RoomId = 19;
EXEC changeRoomPerson  @PersonId = 7, @RoomId = 19;
EXEC changeRoomPerson  @PersonId = 9, @RoomId = 19;
EXEC changeRoomPerson  @PersonId = 11, @RoomId = 20;
EXEC changeRoomPerson  @PersonId = 13, @RoomId = 20;
EXEC changeRoomPerson  @PersonId = 15, @RoomId = 20;
EXEC changeRoomPerson  @PersonId = 10, @RoomId = 11;
EXEC changeRoomPerson  @PersonId = 12, @RoomId = 11;
EXEC changeRoomPerson  @PersonId = 14, @RoomId = 12;

-- Employees 
EXEC insertEmployee @FirstName='Kermy', @LastName='Sprigging', @JMBG='6852594275903', @QualificationId=1, @GenderId=1, @Telephone='(480) 1606853', @Mobile='856-116-5167', @Email='csprigging0@taobao.com', @ResidanceCityId=31, @ResidanceStreetName='Thompson', @ResidanceHouseNumber='68042', @BirthDate='1964-11-28', @EmploymentDate='2023-06-19', @BankName='arcu', @BankAccountNumber='LU40 819G AN7N PPPH PHKX', @JobPositionId=3, @EmploymentTypeId=2, @FatherName='Cleavland', @YearsOfExperiance=9, @DaysOfVacation=13, @SchoolName='Mzuzu University', @SchoolQualificationName='Chief Design Engineer', @BirthCityId=22, @BirthCountryId=1;
EXEC insertEmployee @FirstName='Nessa', @LastName='Alesbrook', @JMBG='1577194538231', @QualificationId=1, @GenderId=2, @Telephone=NULL, @Mobile='590-416-3148', @Email='salesbrook1@disqus.com', @ResidanceCityId=45, @ResidanceStreetName='Laurel', @ResidanceHouseNumber='65', @BirthDate='1968-01-02', @EmploymentDate='2023-08-17', @BankName='ipsum aliquam non', @BankAccountNumber='MD05 HXJW TZ3A Z5GT U51R CD7A', @JobPositionId=3, @EmploymentTypeId=2, @FatherName='Sibyl', @YearsOfExperiance=13, @DaysOfVacation=10, @SchoolName='Grodno State Agrarian University', @SchoolQualificationName='Professor', @BirthCityId=25, @BirthCountryId=1;
EXEC insertEmployee @FirstName='Pernell', @LastName='Lentsch', @JMBG='8588280408533', @QualificationId=1, @GenderId=1, @Telephone=NULL, @Mobile='295-329-4280', @Email=NULL, @ResidanceCityId=37, @ResidanceStreetName='Sunnyside', @ResidanceHouseNumber='004', @BirthDate='1999-11-21', @EmploymentDate='2023-02-09', @BankName='in felis donec', @BankAccountNumber='CR85 3274 6433 1608 0593 9', @JobPositionId=3, @EmploymentTypeId=1, @FatherName='Onfre', @YearsOfExperiance=2, @DaysOfVacation=12, @SchoolName='Bar-Ilan University', @SchoolQualificationName='Financial Analyst', @BirthCityId=2, @BirthCountryId=1;
EXEC insertEmployee @FirstName='Shari', @LastName='Smedmore', @JMBG='4927754234661', @QualificationId=1, @GenderId=1, @Telephone='(361) 5217548', @Mobile='152-354-1508', @Email=NULL, @ResidanceCityId=34, @ResidanceStreetName='Main', @ResidanceHouseNumber='74', @BirthDate='1966-05-04', @EmploymentDate='2023-12-11', @BankName='vestibulum', @BankAccountNumber='PK78 BOME PTYJ FJNF A0EA SDPR', @JobPositionId=1, @EmploymentTypeId=2, @FatherName='Obed', @YearsOfExperiance=4, @DaysOfVacation=17, @SchoolName='University of Szczecin', @SchoolQualificationName='Software Test Engineer IV', @BirthCityId=9, @BirthCountryId=1;
EXEC insertEmployee @FirstName='Ysabel', @LastName='Mollnar', @JMBG='6183472228987', @QualificationId=1, @GenderId=1, @Telephone=NULL, @Mobile='753-316-4202', @Email=NULL, @ResidanceCityId=42, @ResidanceStreetName='Carey', @ResidanceHouseNumber='9955', @BirthDate='1963-08-11', @EmploymentDate='2024-01-30', @BankName='dapibus', @BankAccountNumber='BA35 2503 3372 6957 8755', @JobPositionId=1, @EmploymentTypeId=2, @FatherName='Hadrian', @YearsOfExperiance=6, @DaysOfVacation=21, @SchoolName='Shanmugha Arts Science Technology and Research Academy', @SchoolQualificationName='Database Administrator II', @BirthCityId=22, @BirthCountryId=1;
EXEC insertEmployee @FirstName='Janna', @LastName='Crutchley', @JMBG='3616412764030', @QualificationId=1, @GenderId=2, @Telephone=NULL, @Mobile='390-523-1124', @Email='wcrutchley5@independent.co.uk', @ResidanceCityId=15, @ResidanceStreetName='Morningstar', @ResidanceHouseNumber='6372', @BirthDate='1983-04-15', @EmploymentDate='2023-08-24', @BankName='sem', @BankAccountNumber='HU05 4348 6329 4150 7612 8655 9117', @JobPositionId=5, @EmploymentTypeId=1, @FatherName='Willard', @YearsOfExperiance=10, @DaysOfVacation=25, @SchoolName='Montreat College', @SchoolQualificationName='Help Desk Operator', @BirthCityId=47, @BirthCountryId=1;
EXEC insertEmployee @FirstName='Brinn', @LastName='Driffill', @JMBG='1205359675890', @QualificationId=1, @GenderId=1, @Telephone='(126) 1620562', @Mobile='789-532-8026', @Email=NULL, @ResidanceCityId=19, @ResidanceStreetName='Transport', @ResidanceHouseNumber='9', @BirthDate='1967-05-01', @EmploymentDate='2023-07-12', @BankName='massa id lobortis', @BankAccountNumber='MD29 ZH2X NXM4 Z7KG CG9V WG4G', @JobPositionId=2, @EmploymentTypeId=1, @FatherName='Darrel', @YearsOfExperiance=3, @DaysOfVacation=17, @SchoolName='Karaganda State Buketov University', @SchoolQualificationName='Marketing Assistant', @BirthCityId=48, @BirthCountryId=1;
EXEC insertEmployee @FirstName='Charlotte', @LastName='Nancekivell', @JMBG='1512781448640', @QualificationId=1, @GenderId=2, @Telephone=NULL, @Mobile='258-573-5084', @Email=NULL, @ResidanceCityId=43, @ResidanceStreetName='Northridge', @ResidanceHouseNumber='067', @BirthDate='1990-04-22', @EmploymentDate='2023-02-03', @BankName='eu pede', @BankAccountNumber='PL69 8856 8286 5541 1109 5349 2653', @JobPositionId=1, @EmploymentTypeId=1, @FatherName='Maje', @YearsOfExperiance=12, @DaysOfVacation=18, @SchoolName='Universidad México Americana del Norte', @SchoolQualificationName='Internal Auditor', @BirthCityId=47, @BirthCountryId=1;
EXEC insertEmployee @FirstName='Lorin', @LastName='Gregh', @JMBG='0830942508961', @QualificationId=1, @GenderId=2, @Telephone=NULL, @Mobile='692-755-5952', @Email='ggregh8@npr.org', @ResidanceCityId=35, @ResidanceStreetName='Onsgard', @ResidanceHouseNumber='651', @BirthDate='1965-12-04', @EmploymentDate='2023-05-11', @BankName='dui luctus rutrum', @BankAccountNumber='KZ23 405O ITS0 O04D CEYF', @JobPositionId=3, @EmploymentTypeId=2, @FatherName='Gaspar', @YearsOfExperiance=4, @DaysOfVacation=18, @SchoolName='Carnegie Mellon University', @SchoolQualificationName='Clinical Specialist', @BirthCityId=45, @BirthCountryId=1;
EXEC insertEmployee @FirstName='Myrtie', @LastName='Burnside', @JMBG='8775700721310', @QualificationId=1, @GenderId=1, @Telephone=NULL, @Mobile='793-865-8849', @Email='tburnside9@merriam-webster.com', @ResidanceCityId=29, @ResidanceStreetName='Village', @ResidanceHouseNumber='90940', @BirthDate='1985-05-23', @EmploymentDate='2024-02-07', @BankName='suspendisse potenti', @BankAccountNumber='KW83 EJQP 1RLU BMNL RYMK HL2L KKOR O2', @JobPositionId=1, @EmploymentTypeId=2, @FatherName='Town', @YearsOfExperiance=8, @DaysOfVacation=24, @SchoolName='College of Technology at Abha', @SchoolQualificationName='Web Developer IV', @BirthCityId=15, @BirthCountryId=1;

-- Services
EXEC insertService @Name='Acridotheres tristis', @Description='Curabitur at ipsum ac tellus semper interdum.', @MeasureUnitId=3, @CostPerUnit=324.37, @PriceUnitId=1;
EXEC insertService @Name='Coluber constrictor', @Description='Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', @MeasureUnitId=3, @CostPerUnit=329.98, @PriceUnitId=1;
EXEC insertService @Name='Ourebia ourebi', @Description='Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', @MeasureUnitId=3, @CostPerUnit=91.88, @PriceUnitId=1;
EXEC insertService @Name='Hyaena hyaena', @Description='Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', @MeasureUnitId=2, @CostPerUnit=36.45, @PriceUnitId=1;
EXEC insertService @Name='Vulpes chama', @Description='Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', @MeasureUnitId=2, @CostPerUnit=81.43, @PriceUnitId=1;
EXEC insertService @Name='Theropithecus gelada', @Description='Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', @MeasureUnitId=2, @CostPerUnit=391.13, @PriceUnitId=1;
EXEC insertService @Name='Canis dingo', @Description='Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', @MeasureUnitId=3, @CostPerUnit=112.94, @PriceUnitId=1;
EXEC insertService @Name='Gymnorhina tibicen', @Description='Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', @MeasureUnitId=1, @CostPerUnit=311.35, @PriceUnitId=1;
EXEC insertService @Name='Ciconia ciconia', @Description='Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', @MeasureUnitId=1, @CostPerUnit=70.78, @PriceUnitId=1;
EXEC insertService @Name='Stenella coeruleoalba', @Description='Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', @MeasureUnitId=1, @CostPerUnit=113.58, @PriceUnitId=1;
EXEC insertService @Name='Cereopsis novaehollandiae', @Description='Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', @MeasureUnitId=1, @CostPerUnit=486.66, @PriceUnitId=1;
EXEC insertService @Name='Kobus defassa', @Description='Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', @MeasureUnitId=4, @CostPerUnit=459.97, @PriceUnitId=1;
EXEC insertService @Name='Zalophus californicus', @Description='Aliquam erat volutpat.', @MeasureUnitId=2, @CostPerUnit=334.7, @PriceUnitId=1;
EXEC insertService @Name='Sula dactylatra', @Description='Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', @MeasureUnitId=3, @CostPerUnit=455.41, @PriceUnitId=1;
EXEC insertService @Name='Isoodon obesulus', @Description='In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', @MeasureUnitId=4, @CostPerUnit=156.4, @PriceUnitId=1;
EXEC insertService @Name='Agelaius phoeniceus', @Description='Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', @MeasureUnitId=3, @CostPerUnit=56.24, @PriceUnitId=1;
EXEC insertService @Name='Fratercula corniculata', @Description='Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', @MeasureUnitId=2, @CostPerUnit=293.33, @PriceUnitId=1;
EXEC insertService @Name='Sarkidornis melanotos', @Description='Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', @MeasureUnitId=3, @CostPerUnit=454.93, @PriceUnitId=1;
EXEC insertService @Name='Vulpes cinereoargenteus', @Description='Nunc purus. Phasellus in felis. Donec semper sapien a libero.', @MeasureUnitId=3, @CostPerUnit=428.28, @PriceUnitId=1;
EXEC insertService @Name='Mazama gouazoubira', @Description='Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', @MeasureUnitId=3, @CostPerUnit=137.13, @PriceUnitId=1;
EXEC insertService @Name='unavailable', @Description='Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', @MeasureUnitId=1, @CostPerUnit=269.06, @PriceUnitId=1;
EXEC insertService @Name='Carphophis sp.', @Description='Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', @MeasureUnitId=1, @CostPerUnit=365.28, @PriceUnitId=1;
EXEC insertService @Name='Phoenicopterus ruber', @Description='Ut at dolor quis odio consequat varius. Integer ac leo.', @MeasureUnitId=2, @CostPerUnit=227.4, @PriceUnitId=1;
EXEC insertService @Name='Milvus migrans', @Description='Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', @MeasureUnitId=4, @CostPerUnit=238.46, @PriceUnitId=1;
EXEC insertService @Name='Rhea americana', @Description='Phasellus in felis. Donec semper sapien a libero. Nam dui.', @MeasureUnitId=2, @CostPerUnit=317.91, @PriceUnitId=1;
EXEC insertService @Name='Buteo jamaicensis', @Description='Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', @MeasureUnitId=4, @CostPerUnit=495.25, @PriceUnitId=1;
EXEC insertService @Name='Chlamydosaurus kingii', @Description='In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', @MeasureUnitId=3, @CostPerUnit=340.15, @PriceUnitId=1;
EXEC insertService @Name='Limnocorax flavirostra', @Description='Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', @MeasureUnitId=4, @CostPerUnit=178.38, @PriceUnitId=1;
EXEC insertService @Name='Lutra canadensis', @Description='Aliquam erat volutpat. In congue. Etiam justo.', @MeasureUnitId=2, @CostPerUnit=163.88, @PriceUnitId=1;
EXEC insertService @Name='Coluber constrictor', @Description='Morbi non quam nec dui luctus rutrum. Nulla tellus.', @MeasureUnitId=2, @CostPerUnit=98.59, @PriceUnitId=1;
EXEC insertService @Name='Phascogale calura', @Description='Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', @MeasureUnitId=4, @CostPerUnit=257.0, @PriceUnitId=1;
EXEC insertService @Name='Hyaena hyaena', @Description='Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.', @MeasureUnitId=4, @CostPerUnit=117.0, @PriceUnitId=1;
EXEC insertService @Name='Uraeginthus granatina', @Description='Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', @MeasureUnitId=3, @CostPerUnit=88.06, @PriceUnitId=1;
EXEC insertService @Name='Bradypus tridactylus', @Description='Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', @MeasureUnitId=2, @CostPerUnit=438.93, @PriceUnitId=1;
EXEC insertService @Name='Speothos vanaticus', @Description='Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', @MeasureUnitId=3, @CostPerUnit=325.19, @PriceUnitId=1;
EXEC insertService @Name='Antilope cervicapra', @Description='Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', @MeasureUnitId=3, @CostPerUnit=296.35, @PriceUnitId=1;
EXEC insertService @Name='Coluber constrictor foxii', @Description='Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', @MeasureUnitId=4, @CostPerUnit=6.81, @PriceUnitId=1;
EXEC insertService @Name='Taurotagus oryx', @Description='Nullam varius.', @MeasureUnitId=2, @CostPerUnit=362.35, @PriceUnitId=1;
EXEC insertService @Name='unavailable', @Description='Nunc purus. Phasellus in felis. Donec semper sapien a libero.', @MeasureUnitId=3, @CostPerUnit=353.34, @PriceUnitId=1;
EXEC insertService @Name='Dicrostonyx groenlandicus', @Description='Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', @MeasureUnitId=3, @CostPerUnit=152.9, @PriceUnitId=1;
EXEC insertService @Name='Psophia viridis', @Description='Nunc nisl.', @MeasureUnitId=2, @CostPerUnit=358.98, @PriceUnitId=1;
EXEC insertService @Name='Eumetopias jubatus', @Description='Aliquam erat volutpat.', @MeasureUnitId=4, @CostPerUnit=301.7, @PriceUnitId=1;
EXEC insertService @Name='Mungos mungo', @Description='Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', @MeasureUnitId=1, @CostPerUnit=414.15, @PriceUnitId=1;
EXEC insertService @Name='Lama guanicoe', @Description='Sed vel enim sit amet nunc viverra dapibus.', @MeasureUnitId=2, @CostPerUnit=147.65, @PriceUnitId=1;
EXEC insertService @Name='Axis axis', @Description='Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', @MeasureUnitId=1, @CostPerUnit=386.22, @PriceUnitId=1;
EXEC insertService @Name='Antechinus flavipes', @Description='Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', @MeasureUnitId=1, @CostPerUnit=475.03, @PriceUnitId=1;
EXEC insertService @Name='Bison bison', @Description='Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', @MeasureUnitId=4, @CostPerUnit=423.73, @PriceUnitId=1;
EXEC insertService @Name='Meleagris gallopavo', @Description='Quisque id justo sit amet sapien dignissim vestibulum.', @MeasureUnitId=1, @CostPerUnit=366.71, @PriceUnitId=1;
EXEC insertService @Name='Panthera pardus', @Description='Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', @MeasureUnitId=2, @CostPerUnit=155.16, @PriceUnitId=1;
EXEC insertService @Name='Coendou prehensilis', @Description='Morbi a ipsum. Integer a nibh.', @MeasureUnitId=1, @CostPerUnit=304.51, @PriceUnitId=1;

-- Packages
EXEC insertPackage @Name='Package 1', @Description='Morbi a ipsum. Integer a nibh.', @CalculationMeasureUnitId=2, @DefaultPackagePrice=1000.00, @DefaultPackagePriceUnitId=1, @PackagePriceCalculated=0;
EXEC insertPackage @Name='Package 2', @Description='Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', @CalculationMeasureUnitId=2, @DefaultPackagePrice=2000.00, @DefaultPackagePriceUnitId=1, @PackagePriceCalculated=0;
EXEC insertPackage @Name='Package 3', @Description='Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', @CalculationMeasureUnitId=2, @DefaultPackagePrice=NULL, @DefaultPackagePriceUnitId=1, @PackagePriceCalculated=1;

EXEC insertServiceForPackage @ServiceId=1, @PackageId=1, @Quantity=1;
EXEC insertServiceForPackage @ServiceId=2, @PackageId=1, @Quantity=3;
EXEC insertServiceForPackage @ServiceId=3, @PackageId=1, @Quantity=1;
EXEC insertServiceForPackage @ServiceId=4, @PackageId=1, @Quantity=10;
EXEC insertServiceForPackage @ServiceId=5, @PackageId=1, @Quantity=1;
EXEC insertServiceForPackage @ServiceId=6, @PackageId=1, @Quantity=5;
EXEC insertServiceForPackage @ServiceId=7, @PackageId=1, @Quantity=1;
EXEC insertServiceForPackage @ServiceId=8, @PackageId=1, @Quantity=6;
EXEC insertServiceForPackage @ServiceId=9, @PackageId=1, @Quantity=1;
EXEC insertServiceForPackage @ServiceId=10, @PackageId=1, @Quantity=2;

EXEC insertServiceForPackage @ServiceId=1, @PackageId=2, @Quantity=2;
EXEC insertServiceForPackage @ServiceId=2, @PackageId=2, @Quantity=3;
EXEC insertServiceForPackage @ServiceId=3, @PackageId=2, @Quantity=1;
EXEC insertServiceForPackage @ServiceId=4, @PackageId=2, @Quantity=1;
EXEC insertServiceForPackage @ServiceId=5, @PackageId=2, @Quantity=1;

EXEC insertServiceForPackage @ServiceId=6, @PackageId=3, @Quantity=5;
EXEC insertServiceForPackage @ServiceId=7, @PackageId=3, @Quantity=1;
EXEC insertServiceForPackage @ServiceId=8, @PackageId=3, @Quantity=6;
EXEC insertServiceForPackage @ServiceId=9, @PackageId=3, @Quantity=1;
EXEC insertServiceForPackage @ServiceId=10, @PackageId=3, @Quantity=2;

-- Packages and services for person
EXEC insertPackageForPerson @PersonId=1, @PackageId=1;
EXEC insertPackageForPerson @PersonId=2, @PackageId=2;
EXEC insertPackageForPerson @PersonId=3, @PackageId=3;
EXEC insertPackageForPerson @PersonId=4, @PackageId=1;
EXEC insertPackageForPerson @PersonId=5, @PackageId=2;
EXEC insertPackageForPerson @PersonId=6, @PackageId=3;
EXEC insertPackageForPerson @PersonId=7, @PackageId=1;
EXEC insertPackageForPerson @PersonId=8, @PackageId=1;
EXEC insertPackageForPerson @PersonId=9, @PackageId=1;
EXEC insertPackageForPerson @PersonId=10, @PackageId=2;
EXEC insertPackageForPerson @PersonId=11, @PackageId=2;
EXEC insertPackageForPerson @PersonId=12, @PackageId=3;
EXEC insertPackageForPerson @PersonId=13, @PackageId=3;
EXEC insertPackageForPerson @PersonId=14, @PackageId=2;
EXEC insertPackageForPerson @PersonId=15, @PackageId=1;

EXEC insertServiceForPerson @PersonId=1, @ServiceId=5, @Quantity=1;
EXEC insertServiceForPerson @PersonId=1, @ServiceId=10, @Quantity=2;
EXEC insertServiceForPerson @PersonId=1, @ServiceId=15, @Quantity=1;
EXEC insertServiceForPerson @PersonId=1, @ServiceId=6, @Quantity=1;

EXEC insertServiceForPerson @PersonId=2, @ServiceId=5, @Quantity=3;
EXEC insertServiceForPerson @PersonId=2, @ServiceId=10, @Quantity=1;
EXEC insertServiceForPerson @PersonId=2, @ServiceId=15, @Quantity=1;
EXEC insertServiceForPerson @PersonId=2, @ServiceId=6, @Quantity=1;

EXEC insertOfferMeasureUnitForPerson @PersonId=1, @MeasureUnitId=2;
EXEC insertOfferMeasureUnitForPerson @PersonId=2, @MeasureUnitId=2;
EXEC insertOfferMeasureUnitForPerson @PersonId=3, @MeasureUnitId=2;
EXEC insertOfferMeasureUnitForPerson @PersonId=4, @MeasureUnitId=2;
EXEC insertOfferMeasureUnitForPerson @PersonId=5, @MeasureUnitId=2;
EXEC insertOfferMeasureUnitForPerson @PersonId=6, @MeasureUnitId=2;
EXEC insertOfferMeasureUnitForPerson @PersonId=7, @MeasureUnitId=2;
EXEC insertOfferMeasureUnitForPerson @PersonId=8, @MeasureUnitId=2;
EXEC insertOfferMeasureUnitForPerson @PersonId=9, @MeasureUnitId=2;
EXEC insertOfferMeasureUnitForPerson @PersonId=10, @MeasureUnitId=2;
EXEC insertOfferMeasureUnitForPerson @PersonId=11, @MeasureUnitId=2;
EXEC insertOfferMeasureUnitForPerson @PersonId=12, @MeasureUnitId=2;
EXEC insertOfferMeasureUnitForPerson @PersonId=13, @MeasureUnitId=2;
EXEC insertOfferMeasureUnitForPerson @PersonId=14, @MeasureUnitId=2;
EXEC insertOfferMeasureUnitForPerson @PersonId=15, @MeasureUnitId=2;

-- Notes for person
EXEC insertNote @PersonId=3, @Title='Integer ac leo.', @Text='Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', @Tags='4,2';
EXEC insertNote @PersonId=5, @Title='Nam dui.', @Text='Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', @Tags='4,2';
EXEC insertNote @PersonId=2, @Title='In quis justo.', @Text='Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', @Tags='4,2';
EXEC insertNote @PersonId=9, @Title='Pellentesque ultrices mattis odio.', @Text='Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', @Tags='4,2';
EXEC insertNote @PersonId=13, @Title='Nulla ut erat id mauris vulputate elementum.', @Text='Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', @Tags='4,2';
EXEC insertNote @PersonId=12, @Title='Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', @Text='Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', @Tags='4,2';
EXEC insertNote @PersonId=9, @Title='Suspendisse potenti.', @Text='Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', @Tags='4,2';
EXEC insertNote @PersonId=9, @Title='Suspendisse ornare consequat lectus.', @Text='Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.', @Tags='4,2';
EXEC insertNote @PersonId=15, @Title='Donec semper sapien a libero.', @Text='In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', @Tags='4,2';
EXEC insertNote @PersonId=5, @Title='Suspendisse potenti.', @Text='Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', @Tags='4,2';
EXEC insertNote @PersonId=4, @Title='Nullam molestie nibh in lectus.', @Text='Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', @Tags='4,2';
EXEC insertNote @PersonId=5, @Title='Duis mattis egestas metus.', @Text='Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', @Tags='4,2';
EXEC insertNote @PersonId=12, @Title='Nullam porttitor lacus at turpis.', @Text='Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', @Tags='4,2';
EXEC insertNote @PersonId=12, @Title='Aliquam quis turpis eget elit sodales scelerisque.', @Text='Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', @Tags='4,2';
EXEC insertNote @PersonId=1, @Title='Nullam varius.', @Text='Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.', @Tags='4,2';
EXEC insertNote @PersonId=8, @Title='Suspendisse potenti.', @Text='Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', @Tags='4,2';
EXEC insertNote @PersonId=15, @Title='Quisque ut erat.', @Text='Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', @Tags='4,2';
EXEC insertNote @PersonId=6, @Title='Integer ac leo.', @Text='Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', @Tags='4,2';
EXEC insertNote @PersonId=11, @Title='Sed sagittis.', @Text='Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', @Tags='4,2';
EXEC insertNote @PersonId=13, @Title='Proin interdum mauris non ligula pellentesque ultrices.', @Text='Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', @Tags='4,2';
EXEC insertNote @PersonId=12, @Title='Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', @Text='Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', @Tags='4,2';
EXEC insertNote @PersonId=3, @Title='Nulla mollis molestie lorem.', @Text='Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', @Tags='4,2';
EXEC insertNote @PersonId=6, @Title='Praesent blandit.', @Text='Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', @Tags='4,2';
EXEC insertNote @PersonId=9, @Title='Duis aliquam convallis nunc.', @Text='Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.', @Tags='4,2';
EXEC insertNote @PersonId=5, @Title='Duis ac nibh.', @Text='Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', @Tags='4,2';
EXEC insertNote @PersonId=13, @Title='Phasellus id sapien in sapien iaculis congue.', @Text='Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', @Tags='4,2';
EXEC insertNote @PersonId=11, @Title='Vivamus vestibulum sagittis sapien.', @Text='Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', @Tags='4,2';
EXEC insertNote @PersonId=7, @Title='Nullam varius.', @Text='Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', @Tags='4,2';
EXEC insertNote @PersonId=6, @Title='Duis ac nibh.', @Text='Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', @Tags='4,2';
EXEC insertNote @PersonId=6, @Title='Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', @Text='In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', @Tags='4,2';

-- Furniture
EXEC insertFurniture @Name='Oil & Gas Production', @Description='Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', @InventoryCode='62011-0002', @RoomId=17;
EXEC insertFurniture @Name='Clothing/Shoe/Accessory Stores', @Description='Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', @InventoryCode='0078-0563', @RoomId=8;
EXEC insertFurniture @Name='n/a', @Description='Suspendisse accumsan tortor quis turpis. Sed ante.', @InventoryCode='55289-310', @RoomId=NULL;
EXEC insertFurniture @Name='EDP Services', @Description='Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', @InventoryCode='36987-3098', @RoomId=2;
EXEC insertFurniture @Name='n/a', @Description='Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.', @InventoryCode='63868-812', @RoomId=4;
EXEC insertFurniture @Name='Major Pharmaceuticals', @Description='Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', @InventoryCode='36987-2925', @RoomId=14;
EXEC insertFurniture @Name='Commercial Banks', @Description='Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', @InventoryCode='52584-119', @RoomId=7;
EXEC insertFurniture @Name='n/a', @Description='Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', @InventoryCode='0591-0240', @RoomId=NULL;
EXEC insertFurniture @Name='Professional Services', @Description='Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', @InventoryCode='43269-818', @RoomId=1;
EXEC insertFurniture @Name='Automotive Aftermarket', @Description='Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', @InventoryCode='51672-5292', @RoomId=NULL;
EXEC insertFurniture @Name='Diversified Financial Services', @Description='In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', @InventoryCode='66435-410', @RoomId=16;
EXEC insertFurniture @Name='n/a', @Description='Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', @InventoryCode='0603-4082', @RoomId=6;
EXEC insertFurniture @Name='Industrial Machinery/Components', @Description='Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.', @InventoryCode='37012-127', @RoomId=7;
EXEC insertFurniture @Name='Semiconductors', @Description='Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', @InventoryCode='65841-750', @RoomId=NULL;
EXEC insertFurniture @Name='Railroads', @Description='Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.', @InventoryCode='41167-0093', @RoomId=1;
EXEC insertFurniture @Name='Office Equipment/Supplies/Services', @Description='Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', @InventoryCode='59779-920', @RoomId=7;
EXEC insertFurniture @Name='n/a', @Description='Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', @InventoryCode='10191-1248', @RoomId=11;
EXEC insertFurniture @Name='Real Estate', @Description='In blandit ultrices enim.', @InventoryCode='49349-549', @RoomId=12;
EXEC insertFurniture @Name='Commercial Banks', @Description='Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', @InventoryCode='42291-711', @RoomId=5;
EXEC insertFurniture @Name='Railroads', @Description='Aliquam erat volutpat. In congue. Etiam justo.', @InventoryCode='50593-003', @RoomId=NULL;
EXEC insertFurniture @Name='Telecommunications Equipment', @Description='Praesent blandit. Nam nulla.', @InventoryCode='63629-3767', @RoomId=NULL;
EXEC insertFurniture @Name='Power Generation', @Description='Nulla ut erat id mauris vulputate elementum.', @InventoryCode='13537-560', @RoomId=1;
EXEC insertFurniture @Name='Marine Transportation', @Description='Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', @InventoryCode='56136-002', @RoomId=NULL;
EXEC insertFurniture @Name='Engineering & Construction', @Description='Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', @InventoryCode='0264-5535', @RoomId=NULL;
EXEC insertFurniture @Name='n/a', @Description='Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', @InventoryCode='0904-5782', @RoomId=14;
EXEC insertFurniture @Name='EDP Services', @Description='Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', @InventoryCode='33992-1061', @RoomId=3;
EXEC insertFurniture @Name='Savings Institutions', @Description='Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', @InventoryCode='23710-225', @RoomId=NULL;
EXEC insertFurniture @Name='Business Services', @Description='Morbi non quam nec dui luctus rutrum.', @InventoryCode='43857-0171', @RoomId=4;
EXEC insertFurniture @Name='Major Pharmaceuticals', @Description='Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', @InventoryCode='16590-401', @RoomId=6;
EXEC insertFurniture @Name='Computer Software: Prepackaged Software', @Description='Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', @InventoryCode='41250-959', @RoomId=10;
EXEC insertFurniture @Name='Major Pharmaceuticals', @Description='Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', @InventoryCode='49643-008', @RoomId=3;
EXEC insertFurniture @Name='n/a', @Description='Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', @InventoryCode='43455-0004', @RoomId=3;
EXEC insertFurniture @Name='Major Banks', @Description='Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', @InventoryCode='43353-857', @RoomId=3;
EXEC insertFurniture @Name='Major Banks', @Description='Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', @InventoryCode='76125-784', @RoomId=NULL;
EXEC insertFurniture @Name='Ordnance And Accessories', @Description='Proin risus. Praesent lectus.', @InventoryCode='13537-266', @RoomId=2;
EXEC insertFurniture @Name='Real Estate Investment Trusts', @Description='Aenean sit amet justo.', @InventoryCode='49035-131', @RoomId=1;
EXEC insertFurniture @Name='Electric Utilities: Central', @Description='Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', @InventoryCode='17630-2005', @RoomId=7;
EXEC insertFurniture @Name='Real Estate Investment Trusts', @Description='Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.', @InventoryCode='24385-036', @RoomId=8;
EXEC insertFurniture @Name='n/a', @Description='Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', @InventoryCode='0187-0731', @RoomId=15;
EXEC insertFurniture @Name='Real Estate Investment Trusts', @Description='In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', @InventoryCode='68604-238', @RoomId=13;
EXEC insertFurniture @Name='Farming/Seeds/Milling', @Description='Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', @InventoryCode='67510-0507', @RoomId=7;
EXEC insertFurniture @Name='n/a', @Description='Nullam molestie nibh in lectus. Pellentesque at nulla.', @InventoryCode='59779-884', @RoomId=19;
EXEC insertFurniture @Name='Diversified Commercial Services', @Description='Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', @InventoryCode='0781-2104', @RoomId=5;
EXEC insertFurniture @Name='Building Products', @Description='Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', @InventoryCode='36800-441', @RoomId=4;
EXEC insertFurniture @Name='Specialty Insurers', @Description='Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', @InventoryCode='0093-5514', @RoomId=NULL;
EXEC insertFurniture @Name='Real Estate Investment Trusts', @Description='Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', @InventoryCode='61715-062', @RoomId=3;
EXEC insertFurniture @Name='Major Pharmaceuticals', @Description='Proin eu mi.', @InventoryCode='64725-4005', @RoomId=NULL;
EXEC insertFurniture @Name='Industrial Machinery/Components', @Description='Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', @InventoryCode='0781-3317', @RoomId=16;
EXEC insertFurniture @Name='Real Estate Investment Trusts', @Description='Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', @InventoryCode='63940-334', @RoomId=NULL;
EXEC insertFurniture @Name='n/a', @Description='Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', @InventoryCode='70253-392', @RoomId=NULL;
EXEC insertFurniture @Name='Hospital/Nursing Management', @Description='In quis justo.', @InventoryCode='68968-5554', @RoomId=NULL;
EXEC insertFurniture @Name='n/a', @Description='Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', @InventoryCode='59779-576', @RoomId=17;
EXEC insertFurniture @Name='Medical Electronics', @Description='Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', @InventoryCode='52959-733', @RoomId=NULL;
EXEC insertFurniture @Name='Forest Products', @Description='Duis bibendum.', @InventoryCode='36987-1602', @RoomId=18;
EXEC insertFurniture @Name='Real Estate Investment Trusts', @Description='Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', @InventoryCode='53014-975', @RoomId=18;
EXEC insertFurniture @Name='Professional Services', @Description='Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', @InventoryCode='0615-6502', @RoomId=11;
EXEC insertFurniture @Name='Industrial Machinery/Components', @Description='Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', @InventoryCode='64376-657', @RoomId=NULL;
EXEC insertFurniture @Name='Electrical Products', @Description='Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', @InventoryCode='64058-153', @RoomId=NULL;
EXEC insertFurniture @Name='n/a', @Description='Morbi porttitor lorem id ligula.', @InventoryCode='0069-2260', @RoomId=18;
EXEC insertFurniture @Name='Telecommunications Equipment', @Description='Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', @InventoryCode='0143-9858', @RoomId=13;
EXEC insertFurniture @Name='Other Consumer Services', @Description='Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', @InventoryCode='60512-1031', @RoomId=NULL;
EXEC insertFurniture @Name='Precious Metals', @Description='Pellentesque viverra pede ac diam.', @InventoryCode='51346-136', @RoomId=NULL;
EXEC insertFurniture @Name='Investment Bankers/Brokers/Service', @Description='In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', @InventoryCode='0944-4351', @RoomId=9;
EXEC insertFurniture @Name='Real Estate Investment Trusts', @Description='Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', @InventoryCode='0904-0053', @RoomId=NULL;
EXEC insertFurniture @Name='Homebuilding', @Description='Curabitur in libero ut massa volutpat convallis.', @InventoryCode='45264-009', @RoomId=10;
EXEC insertFurniture @Name='Commercial Banks', @Description='In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', @InventoryCode='51442-544', @RoomId=19;
EXEC insertFurniture @Name='Other Consumer Services', @Description='Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', @InventoryCode='10812-171', @RoomId=18;
EXEC insertFurniture @Name='Home Furnishings', @Description='Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', @InventoryCode='68093-7091', @RoomId=1;
EXEC insertFurniture @Name='Major Pharmaceuticals', @Description='Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', @InventoryCode='54868-4476', @RoomId=NULL;
EXEC insertFurniture @Name='Computer Software: Programming, Data Processing', @Description='Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', @InventoryCode='51346-074', @RoomId=14;
EXEC insertFurniture @Name='Electronic Components', @Description='Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', @InventoryCode='60637-016', @RoomId=NULL;
EXEC insertFurniture @Name='Restaurants', @Description='Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', @InventoryCode='49035-404', @RoomId=NULL;
EXEC insertFurniture @Name='n/a', @Description='Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', @InventoryCode='68428-056', @RoomId=10;
EXEC insertFurniture @Name='n/a', @Description='Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', @InventoryCode='58232-0318', @RoomId=5;
EXEC insertFurniture @Name='n/a', @Description='Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', @InventoryCode='0065-0530', @RoomId=12;
EXEC insertFurniture @Name='n/a', @Description='Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', @InventoryCode='36987-2990', @RoomId=7;
EXEC insertFurniture @Name='Other Specialty Stores', @Description='Vivamus vel nulla eget eros elementum pellentesque.', @InventoryCode='59779-664', @RoomId=NULL;
EXEC insertFurniture @Name='Publishing', @Description='Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', @InventoryCode='48951-1025', @RoomId=10;
EXEC insertFurniture @Name='Homebuilding', @Description='Donec dapibus. Duis at velit eu est congue elementum.', @InventoryCode='54868-3438', @RoomId=2;
EXEC insertFurniture @Name='Major Banks', @Description='Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', @InventoryCode='61748-012', @RoomId=8;
EXEC insertFurniture @Name='Business Services', @Description='Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', @InventoryCode='52959-219', @RoomId=NULL;
EXEC insertFurniture @Name='n/a', @Description='Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', @InventoryCode='21695-797', @RoomId=NULL;
EXEC insertFurniture @Name='n/a', @Description='Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', @InventoryCode='53329-641', @RoomId=4;
EXEC insertFurniture @Name='Industrial Specialties', @Description='Nam dui.', @InventoryCode='50988-179', @RoomId=14;
EXEC insertFurniture @Name='Investment Managers', @Description='Sed ante. Vivamus tortor. Duis mattis egestas metus.', @InventoryCode='63981-612', @RoomId=13;
EXEC insertFurniture @Name='Major Banks', @Description='Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', @InventoryCode='15071-672', @RoomId=NULL;
EXEC insertFurniture @Name='Medical/Dental Instruments', @Description='Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', @InventoryCode='68647-176', @RoomId=7;
EXEC insertFurniture @Name='Major Banks', @Description='Nam nulla.', @InventoryCode='64455-993', @RoomId=3;
EXEC insertFurniture @Name='Major Banks', @Description='Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', @InventoryCode='15310-010', @RoomId=4;
EXEC insertFurniture @Name='Major Pharmaceuticals', @Description='Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', @InventoryCode='54868-1971', @RoomId=9;
EXEC insertFurniture @Name='Electric Utilities: Central', @Description='Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', @InventoryCode='0088-2500', @RoomId=9;
EXEC insertFurniture @Name='Commercial Banks', @Description='Nulla mollis molestie lorem. Quisque ut erat.', @InventoryCode='51824-026', @RoomId=NULL;
EXEC insertFurniture @Name='Medical Specialities', @Description='Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', @InventoryCode='52533-080', @RoomId=6;
EXEC insertFurniture @Name='Marine Transportation', @Description='Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', @InventoryCode='0615-7773', @RoomId=NULL;
EXEC insertFurniture @Name='Medical Specialities', @Description='Nunc nisl.', @InventoryCode='63739-809', @RoomId=1;
EXEC insertFurniture @Name='Specialty Insurers', @Description='Pellentesque at nulla.', @InventoryCode='21130-044', @RoomId=3;
EXEC insertFurniture @Name='Building Materials', @Description='In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', @InventoryCode='52584-978', @RoomId=4;
EXEC insertFurniture @Name='n/a', @Description='Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', @InventoryCode='52125-904', @RoomId=15;
EXEC insertFurniture @Name='Industrial Specialties', @Description='Aliquam erat volutpat. In congue. Etiam justo.', @InventoryCode='62149-0002', @RoomId=NULL;
EXEC insertFurniture @Name='n/a', @Description='Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', @InventoryCode='0178-0089', @RoomId=11;

EXEC changeFurnitureStatus @Id=17, @StatusId=2, @StatusDate='2023-07-22 14:24:27';
EXEC changeFurnitureStatus @Id=97, @StatusId=1, @StatusDate='2023-03-05 07:54:02';
EXEC changeFurnitureStatus @Id=93, @StatusId=2, @StatusDate='2023-02-05 13:11:00';
EXEC changeFurnitureStatus @Id=26, @StatusId=2, @StatusDate='2023-02-13 17:15:21';
EXEC changeFurnitureStatus @Id=98, @StatusId=3, @StatusDate='2023-06-07 18:11:08';
EXEC changeFurnitureStatus @Id=49, @StatusId=2, @StatusDate='2023-11-17 18:20:21';
EXEC changeFurnitureStatus @Id=34, @StatusId=3, @StatusDate='2023-08-28 19:26:14';
EXEC changeFurnitureStatus @Id=90, @StatusId=2, @StatusDate='2023-12-23 05:09:18';
EXEC changeFurnitureStatus @Id=66, @StatusId=1, @StatusDate='2024-03-12 22:59:46';
EXEC changeFurnitureStatus @Id=96, @StatusId=3, @StatusDate='2023-05-22 08:30:47';
EXEC changeFurnitureStatus @Id=47, @StatusId=1, @StatusDate='2023-02-12 12:03:39';
EXEC changeFurnitureStatus @Id=33, @StatusId=1, @StatusDate='2023-04-07 13:15:09';
EXEC changeFurnitureStatus @Id=81, @StatusId=2, @StatusDate='2023-07-14 14:03:40';
EXEC changeFurnitureStatus @Id=54, @StatusId=3, @StatusDate='2023-05-10 11:51:35';
EXEC changeFurnitureStatus @Id=9, @StatusId=1, @StatusDate='2023-02-25 12:37:30';
EXEC changeFurnitureStatus @Id=18, @StatusId=2, @StatusDate='2023-12-12 20:18:04';
EXEC changeFurnitureStatus @Id=35, @StatusId=1, @StatusDate='2023-06-02 09:24:11';
EXEC changeFurnitureStatus @Id=65, @StatusId=2, @StatusDate='2023-09-28 22:23:30';
EXEC changeFurnitureStatus @Id=98, @StatusId=1, @StatusDate='2023-03-21 17:46:50';
EXEC changeFurnitureStatus @Id=24, @StatusId=1, @StatusDate='2023-03-18 13:02:26';
EXEC changeFurnitureStatus @Id=36, @StatusId=1, @StatusDate='2023-05-05 19:00:18';
EXEC changeFurnitureStatus @Id=50, @StatusId=2, @StatusDate='2024-03-23 12:31:57';
EXEC changeFurnitureStatus @Id=26, @StatusId=1, @StatusDate='2023-05-10 05:01:37';
EXEC changeFurnitureStatus @Id=30, @StatusId=1, @StatusDate='2023-05-10 10:32:03';
EXEC changeFurnitureStatus @Id=91, @StatusId=3, @StatusDate='2023-05-08 07:10:49';
EXEC changeFurnitureStatus @Id=45, @StatusId=1, @StatusDate='2024-03-01 21:41:05';
EXEC changeFurnitureStatus @Id=74, @StatusId=3, @StatusDate='2023-08-23 20:15:51';
EXEC changeFurnitureStatus @Id=36, @StatusId=3, @StatusDate='2024-01-15 19:34:09';
EXEC changeFurnitureStatus @Id=47, @StatusId=3, @StatusDate='2023-07-09 18:54:21';
EXEC changeFurnitureStatus @Id=90, @StatusId=3, @StatusDate='2023-01-12 18:26:43';
EXEC changeFurnitureStatus @Id=72, @StatusId=2, @StatusDate='2023-03-22 01:37:24';
EXEC changeFurnitureStatus @Id=20, @StatusId=2, @StatusDate='2024-05-10 11:25:13';
EXEC changeFurnitureStatus @Id=83, @StatusId=1, @StatusDate='2024-03-19 19:41:09';
EXEC changeFurnitureStatus @Id=22, @StatusId=1, @StatusDate='2023-01-24 17:35:07';
EXEC changeFurnitureStatus @Id=64, @StatusId=3, @StatusDate='2023-04-26 04:05:01';
EXEC changeFurnitureStatus @Id=65, @StatusId=2, @StatusDate='2023-12-08 22:34:25';
EXEC changeFurnitureStatus @Id=8, @StatusId=1, @StatusDate='2023-10-27 03:50:16';
EXEC changeFurnitureStatus @Id=36, @StatusId=2, @StatusDate='2023-06-05 18:44:23';
EXEC changeFurnitureStatus @Id=75, @StatusId=2, @StatusDate='2023-04-04 20:35:30';
EXEC changeFurnitureStatus @Id=65, @StatusId=3, @StatusDate='2023-12-23 20:19:16';
EXEC changeFurnitureStatus @Id=20, @StatusId=2, @StatusDate='2023-08-16 01:44:07';
EXEC changeFurnitureStatus @Id=72, @StatusId=2, @StatusDate='2023-09-21 13:37:38';
EXEC changeFurnitureStatus @Id=84, @StatusId=3, @StatusDate='2023-01-20 23:30:35';
EXEC changeFurnitureStatus @Id=61, @StatusId=1, @StatusDate='2023-04-27 20:12:13';
EXEC changeFurnitureStatus @Id=34, @StatusId=3, @StatusDate='2023-12-06 01:16:00';
EXEC changeFurnitureStatus @Id=70, @StatusId=3, @StatusDate='2023-12-06 06:14:55';
EXEC changeFurnitureStatus @Id=8, @StatusId=2, @StatusDate='2023-02-02 08:43:44';
EXEC changeFurnitureStatus @Id=54, @StatusId=1, @StatusDate='2023-10-21 15:41:54';
EXEC changeFurnitureStatus @Id=71, @StatusId=2, @StatusDate='2024-05-04 12:16:28';
EXEC changeFurnitureStatus @Id=65, @StatusId=1, @StatusDate='2024-03-09 23:28:45';
EXEC changeFurnitureStatus @Id=34, @StatusId=1, @StatusDate='2023-04-06 06:01:11';
EXEC changeFurnitureStatus @Id=83, @StatusId=3, @StatusDate='2023-08-13 17:02:12';
EXEC changeFurnitureStatus @Id=97, @StatusId=1, @StatusDate='2023-01-18 21:45:36';
EXEC changeFurnitureStatus @Id=76, @StatusId=2, @StatusDate='2023-11-24 08:25:55';
EXEC changeFurnitureStatus @Id=19, @StatusId=1, @StatusDate='2023-05-14 12:30:39';
EXEC changeFurnitureStatus @Id=12, @StatusId=1, @StatusDate='2023-10-28 23:04:03';
EXEC changeFurnitureStatus @Id=85, @StatusId=3, @StatusDate='2024-02-06 07:22:35';
EXEC changeFurnitureStatus @Id=85, @StatusId=3, @StatusDate='2023-02-18 02:41:16';
EXEC changeFurnitureStatus @Id=97, @StatusId=2, @StatusDate='2023-08-03 03:38:26';
EXEC changeFurnitureStatus @Id=19, @StatusId=3, @StatusDate='2023-09-29 23:40:31';
EXEC changeFurnitureStatus @Id=58, @StatusId=2, @StatusDate='2023-09-25 05:36:37';
EXEC changeFurnitureStatus @Id=63, @StatusId=3, @StatusDate='2023-10-23 08:33:09';
EXEC changeFurnitureStatus @Id=39, @StatusId=1, @StatusDate='2023-07-11 00:53:16';
EXEC changeFurnitureStatus @Id=72, @StatusId=1, @StatusDate='2023-02-19 19:10:42';
EXEC changeFurnitureStatus @Id=63, @StatusId=2, @StatusDate='2023-03-13 03:26:38';
EXEC changeFurnitureStatus @Id=37, @StatusId=3, @StatusDate='2023-05-22 17:12:50';
EXEC changeFurnitureStatus @Id=20, @StatusId=3, @StatusDate='2023-12-29 02:20:47';
EXEC changeFurnitureStatus @Id=96, @StatusId=3, @StatusDate='2023-11-17 07:46:04';
EXEC changeFurnitureStatus @Id=72, @StatusId=1, @StatusDate='2023-12-17 02:58:08';
EXEC changeFurnitureStatus @Id=20, @StatusId=2, @StatusDate='2024-01-14 19:10:09';
EXEC changeFurnitureStatus @Id=7, @StatusId=1, @StatusDate='2024-03-22 19:42:55';
EXEC changeFurnitureStatus @Id=55, @StatusId=3, @StatusDate='2024-01-23 15:01:49';
EXEC changeFurnitureStatus @Id=80, @StatusId=1, @StatusDate='2023-11-18 19:22:00';
EXEC changeFurnitureStatus @Id=57, @StatusId=2, @StatusDate='2024-03-28 06:50:41';
EXEC changeFurnitureStatus @Id=53, @StatusId=3, @StatusDate='2023-12-06 10:10:57';
EXEC changeFurnitureStatus @Id=3, @StatusId=1, @StatusDate='2023-05-28 04:18:48';
EXEC changeFurnitureStatus @Id=72, @StatusId=3, @StatusDate='2023-11-26 19:13:37';
EXEC changeFurnitureStatus @Id=36, @StatusId=1, @StatusDate='2023-03-17 22:58:24';
EXEC changeFurnitureStatus @Id=3, @StatusId=3, @StatusDate='2024-04-22 07:55:20';
EXEC changeFurnitureStatus @Id=96, @StatusId=1, @StatusDate='2023-06-20 05:13:30';
EXEC changeFurnitureStatus @Id=83, @StatusId=1, @StatusDate='2023-06-12 20:07:07';
EXEC changeFurnitureStatus @Id=51, @StatusId=3, @StatusDate='2023-07-14 22:52:17';
EXEC changeFurnitureStatus @Id=29, @StatusId=2, @StatusDate='2023-11-19 04:00:15';
EXEC changeFurnitureStatus @Id=85, @StatusId=3, @StatusDate='2023-05-04 14:00:51';
EXEC changeFurnitureStatus @Id=97, @StatusId=1, @StatusDate='2024-02-20 00:57:42';
EXEC changeFurnitureStatus @Id=44, @StatusId=3, @StatusDate='2023-12-25 02:38:03';
EXEC changeFurnitureStatus @Id=93, @StatusId=3, @StatusDate='2024-04-17 15:41:38';
EXEC changeFurnitureStatus @Id=10, @StatusId=1, @StatusDate='2023-09-20 20:15:43';
EXEC changeFurnitureStatus @Id=2, @StatusId=2, @StatusDate='2023-06-09 03:29:39';
EXEC changeFurnitureStatus @Id=43, @StatusId=3, @StatusDate='2024-03-12 11:56:21';
EXEC changeFurnitureStatus @Id=82, @StatusId=3, @StatusDate='2023-10-31 19:21:08';
EXEC changeFurnitureStatus @Id=95, @StatusId=3, @StatusDate='2024-01-03 15:10:38';
EXEC changeFurnitureStatus @Id=48, @StatusId=2, @StatusDate='2023-05-11 21:50:59';
EXEC changeFurnitureStatus @Id=83, @StatusId=1, @StatusDate='2023-08-30 00:34:31';
EXEC changeFurnitureStatus @Id=3, @StatusId=2, @StatusDate='2023-07-12 17:49:01';
EXEC changeFurnitureStatus @Id=31, @StatusId=3, @StatusDate='2023-11-15 09:16:24';
EXEC changeFurnitureStatus @Id=56, @StatusId=3, @StatusDate='2023-01-16 10:25:57';
EXEC changeFurnitureStatus @Id=39, @StatusId=1, @StatusDate='2023-02-14 07:11:07';
EXEC changeFurnitureStatus @Id=16, @StatusId=2, @StatusDate='2023-11-04 12:57:30';
EXEC changeFurnitureStatus @Id=99, @StatusId=1, @StatusDate='2024-05-01 16:57:33';
EXEC changeFurnitureStatus @Id=98, @StatusId=3, @StatusDate='2023-06-08 23:30:56';
EXEC changeFurnitureStatus @Id=31, @StatusId=2, @StatusDate='2023-08-29 03:20:39';
EXEC changeFurnitureStatus @Id=14, @StatusId=3, @StatusDate='2024-01-20 02:50:12';
EXEC changeFurnitureStatus @Id=64, @StatusId=1, @StatusDate='2023-02-11 13:28:56';
EXEC changeFurnitureStatus @Id=21, @StatusId=3, @StatusDate='2023-10-30 18:51:28';
EXEC changeFurnitureStatus @Id=41, @StatusId=3, @StatusDate='2024-02-15 14:48:31';
EXEC changeFurnitureStatus @Id=93, @StatusId=3, @StatusDate='2023-07-15 07:40:22';
EXEC changeFurnitureStatus @Id=38, @StatusId=3, @StatusDate='2023-09-30 10:50:36';
EXEC changeFurnitureStatus @Id=92, @StatusId=2, @StatusDate='2024-05-01 20:40:01';
EXEC changeFurnitureStatus @Id=70, @StatusId=2, @StatusDate='2023-01-22 17:51:17';
EXEC changeFurnitureStatus @Id=48, @StatusId=2, @StatusDate='2024-01-29 01:08:54';
EXEC changeFurnitureStatus @Id=83, @StatusId=1, @StatusDate='2023-04-21 20:39:05';
EXEC changeFurnitureStatus @Id=44, @StatusId=1, @StatusDate='2023-10-11 16:35:05';
EXEC changeFurnitureStatus @Id=18, @StatusId=3, @StatusDate='2024-02-17 15:40:26';
EXEC changeFurnitureStatus @Id=53, @StatusId=2, @StatusDate='2024-02-05 04:51:13';
EXEC changeFurnitureStatus @Id=2, @StatusId=3, @StatusDate='2023-05-10 23:24:54';
EXEC changeFurnitureStatus @Id=29, @StatusId=2, @StatusDate='2023-07-19 01:55:46';
EXEC changeFurnitureStatus @Id=65, @StatusId=3, @StatusDate='2023-11-04 05:27:58';
EXEC changeFurnitureStatus @Id=67, @StatusId=2, @StatusDate='2024-04-10 12:14:03';
EXEC changeFurnitureStatus @Id=65, @StatusId=2, @StatusDate='2023-08-03 22:40:28';
EXEC changeFurnitureStatus @Id=11, @StatusId=3, @StatusDate='2023-09-20 22:31:40';
EXEC changeFurnitureStatus @Id=89, @StatusId=1, @StatusDate='2023-02-19 07:40:28';
EXEC changeFurnitureStatus @Id=35, @StatusId=3, @StatusDate='2023-12-28 14:16:53';
EXEC changeFurnitureStatus @Id=43, @StatusId=2, @StatusDate='2024-04-02 02:42:15';
EXEC changeFurnitureStatus @Id=77, @StatusId=2, @StatusDate='2023-09-22 02:10:47';
EXEC changeFurnitureStatus @Id=51, @StatusId=1, @StatusDate='2023-10-07 14:10:34';
EXEC changeFurnitureStatus @Id=77, @StatusId=2, @StatusDate='2023-02-05 20:44:55';
EXEC changeFurnitureStatus @Id=22, @StatusId=2, @StatusDate='2023-05-02 14:58:30';
EXEC changeFurnitureStatus @Id=57, @StatusId=1, @StatusDate='2023-07-08 16:42:44';
EXEC changeFurnitureStatus @Id=97, @StatusId=1, @StatusDate='2023-12-03 08:43:04';
EXEC changeFurnitureStatus @Id=31, @StatusId=1, @StatusDate='2023-02-19 15:35:45';
EXEC changeFurnitureStatus @Id=2, @StatusId=2, @StatusDate='2023-05-02 19:35:13';
EXEC changeFurnitureStatus @Id=72, @StatusId=2, @StatusDate='2023-11-01 11:27:23';
EXEC changeFurnitureStatus @Id=32, @StatusId=3, @StatusDate='2024-02-14 11:39:35';
EXEC changeFurnitureStatus @Id=59, @StatusId=3, @StatusDate='2024-02-20 05:40:50';
EXEC changeFurnitureStatus @Id=95, @StatusId=1, @StatusDate='2023-08-06 02:15:09';
EXEC changeFurnitureStatus @Id=47, @StatusId=3, @StatusDate='2024-05-01 23:41:00';
EXEC changeFurnitureStatus @Id=21, @StatusId=3, @StatusDate='2023-03-01 15:30:14';
EXEC changeFurnitureStatus @Id=87, @StatusId=3, @StatusDate='2023-02-06 05:04:52';
EXEC changeFurnitureStatus @Id=87, @StatusId=2, @StatusDate='2023-10-23 02:16:32';
EXEC changeFurnitureStatus @Id=77, @StatusId=1, @StatusDate='2023-08-21 04:38:08';
EXEC changeFurnitureStatus @Id=34, @StatusId=2, @StatusDate='2023-06-24 21:58:39';
EXEC changeFurnitureStatus @Id=27, @StatusId=3, @StatusDate='2024-03-13 01:54:34';
EXEC changeFurnitureStatus @Id=99, @StatusId=2, @StatusDate='2023-04-18 07:31:22';
EXEC changeFurnitureStatus @Id=46, @StatusId=1, @StatusDate='2023-08-09 17:09:30';
EXEC changeFurnitureStatus @Id=22, @StatusId=2, @StatusDate='2023-06-26 02:37:41';
EXEC changeFurnitureStatus @Id=54, @StatusId=3, @StatusDate='2023-07-18 09:16:21';
EXEC changeFurnitureStatus @Id=17, @StatusId=3, @StatusDate='2023-07-13 05:53:25';
EXEC changeFurnitureStatus @Id=33, @StatusId=2, @StatusDate='2023-06-02 14:00:09';
EXEC changeFurnitureStatus @Id=42, @StatusId=1, @StatusDate='2024-02-29 03:39:41';

